import { DateTime } from "luxon";
import type {
  WorkshopEvent,
  WorkshopEventCategory,
} from "@/lib/workshop-types";

const TZ = "America/Los_Angeles";

type CuratedSpec = {
  id: string;
  year: number;
  monthIndex: number;
  day: number;
  hour: number;
  minute: number;
  endHour?: number;
  endMinute?: number;
  timeZone: string;
  title: string;
  tagline: string;
  description: string;
  category: WorkshopEventCategory;
  organizer: string;
  venue: string;
  address: string;
  neighborhood: string;
  rsvpUrl: string;
  sourceChannel: WorkshopEvent["sourceChannel"];
  price?: WorkshopEvent["price"];
};

const CURATED: CuratedSpec[] = [
  {
    id: "la-vromans-linda-codega-20260701",
    year: 2026,
    monthIndex: 6,
    day: 1,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Linda Codega with Petra Lord, — Pasha the Storm",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Linda Codega with Petra Lord, — Pasha the Storm. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-01/linda-codega",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-ray-morton-20260707",
    year: 2026,
    monthIndex: 6,
    day: 7,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Ray Morton — King Kong: The History of a Movie",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Ray Morton — King Kong: The History of a Movie. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-07/ray-morton",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-william-a-hoffman-20260708",
    year: 2026,
    monthIndex: 6,
    day: 8,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "William A. Hoffman — Exploring Southern California: 80 Outings for the Urban Adventurer",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents William A. Hoffman — Exploring Southern California: 80 Outings for the Urban Adventurer. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-08/william-a-hoffman",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-barry-lyga-20260709",
    year: 2026,
    monthIndex: 6,
    day: 9,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Barry Lyga — Every Hunter is Hunted",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Barry Lyga — Every Hunter is Hunted. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-09/barry-lyga",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-jenna-rothberg-20260711",
    year: 2026,
    monthIndex: 6,
    day: 11,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Jenna Rothberg reads from & signs Deli Days",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Jenna Rothberg reads from & signs Deli Days. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-11/jenna-rothberg",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-nadia-paredes-20260711",
    year: 2026,
    monthIndex: 6,
    day: 11,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Nadia Paredes — Art Therapy for Every Day: 365 Tools & Exercises to Help You Create, Heal & Grow",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Nadia Paredes — Art Therapy for Every Day: 365 Tools & Exercises to Help You Create, Heal & Grow. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-11/nadia-paredes",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-marisa-solis-elizabeth-dougherty-20260714",
    year: 2026,
    monthIndex: 6,
    day: 14,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Marisa Solis & Elizabeth Dougherty discuss & sign The Complete Expert-To-Author Guide: Plan, Write, and Publish Your Non",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Marisa Solis & Elizabeth Dougherty discuss & sign The Complete Expert-To-Author Guide: Plan, Write, and Publish Your Non. See listing for RSVP or tickets.",
    category: "workshop",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-14/marisa-solis-elizabeth-dougherty",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-fatimah-asghar-20260715",
    year: 2026,
    monthIndex: 6,
    day: 15,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Fatimah Asghar with Natália Affonso & Aqsa Altaf, — Daughter of the Mountains: Poems of Heartbreak & Homecoming",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Fatimah Asghar with Natália Affonso & Aqsa Altaf, — Daughter of the Mountains: Poems of Heartbreak & Homecoming. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-15/fatimah-asghar",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-shannon-algeo-20260716",
    year: 2026,
    monthIndex: 6,
    day: 16,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Shannon Algeo — The Power in Your Hands: Liberate Yourself from Attachment to Technology",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Shannon Algeo — The Power in Your Hands: Liberate Yourself from Attachment to Technology. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-16/shannon-algeo",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-michael-elias-20260717",
    year: 2026,
    monthIndex: 6,
    day: 17,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Michael Elias with Howard Franklin, — Bender’s L.A.",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Michael Elias with Howard Franklin, — Bender’s L.A.. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-17/michael-elias",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-local-author-day-20260719",
    year: 2026,
    monthIndex: 6,
    day: 19,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Local Author Day Introducing Kimberly Lee",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Local Author Day Introducing Kimberly Lee. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-19/local-author-day",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-alicia-upano-20260720",
    year: 2026,
    monthIndex: 6,
    day: 20,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Alicia Upano with Tarra Stevenson, — Everything to the Sea",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Alicia Upano with Tarra Stevenson, — Everything to the Sea. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-20/alicia-upano",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-dr-niki-elliott-20260721",
    year: 2026,
    monthIndex: 6,
    day: 21,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Dr. Niki Elliott — Heart-Centered Connections: Seven Essential Skills for Helping Neurodiverse and Marginalized Children",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Dr. Niki Elliott — Heart-Centered Connections: Seven Essential Skills for Helping Neurodiverse and Marginalized Children. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-21/dr-niki-elliott",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-vromans-fiction-reading-group-20260722",
    year: 2026,
    monthIndex: 6,
    day: 22,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Vroman's Fiction Reading Group",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Vroman's Fiction Reading Group. See listing for RSVP or tickets.",
    category: "other",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-22/vromans-fiction-reading-group",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-brooke-nevils-20260723",
    year: 2026,
    monthIndex: 6,
    day: 23,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Brooke Nevils — Unspeakable Things: Silence, Shame, and the Stories We Choose to Believe",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Brooke Nevils — Unspeakable Things: Silence, Shame, and the Stories We Choose to Believe. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-07-23/brooke-nevils",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-gregory-orfalea-20260804",
    year: 2026,
    monthIndex: 7,
    day: 4,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Gregory Orfalea — Wonder and Shame",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Gregory Orfalea — Wonder and Shame. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-04/gregory-orfalea",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-dk-furutani-20260805",
    year: 2026,
    monthIndex: 7,
    day: 5,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "D.K. Furutani with Naomi Hirahara, — When Mikan Road Was Ours",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents D.K. Furutani with Naomi Hirahara, — When Mikan Road Was Ours. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-05/dk-furutani",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-ariel-delgado-dixon-20260807",
    year: 2026,
    monthIndex: 7,
    day: 7,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Ariel Delgado Dixon with Sam Cohen, — Sourland",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Ariel Delgado Dixon with Sam Cohen, — Sourland. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-07/ariel-delgado-dixon",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-rey-m-rodriguez-20260809",
    year: 2026,
    monthIndex: 7,
    day: 9,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Rey M. Rodríguez with Obed Silva, — Todos Somos Sagrados/All Are Sacred",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Rey M. Rodríguez with Obed Silva, — Todos Somos Sagrados/All Are Sacred. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-09/rey-m-rodriguez",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-joss-richard-20260810",
    year: 2026,
    monthIndex: 7,
    day: 10,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Joss Richard with Lyla Sage, — Let’s Kiss & Tell",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Joss Richard with Lyla Sage, — Let’s Kiss & Tell. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Pasadena Presbyterian Church",
    address: "585 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-10/joss-richard",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-olivie-blake-20260811",
    year: 2026,
    monthIndex: 7,
    day: 11,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Olivie Blake with Amy Tintera, — Dreamland",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Olivie Blake with Amy Tintera, — Dreamland. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Pasadena Presbyterian Church",
    address: "585 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-11/olivie-blake",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-kate-eberle-20260813",
    year: 2026,
    monthIndex: 7,
    day: 13,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Kate Eberle with Elissa Sussman, — If Books Could Kill",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Kate Eberle with Elissa Sussman, — If Books Could Kill. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-13/kate-eberle",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-bridget-morrissey-20260814",
    year: 2026,
    monthIndex: 7,
    day: 14,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Bridget Morrissey with Vince Rossi, — In What World",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Bridget Morrissey with Vince Rossi, — In What World. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-14/bridget-morrissey",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-april-davila-20260817",
    year: 2026,
    monthIndex: 7,
    day: 17,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "April Dávila with Lian Dolan, — Sit Write Here: 6 Mindfulness Practices to Help You Write More and Suffer Less",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents April Dávila with Lian Dolan, — Sit Write Here: 6 Mindfulness Practices to Help You Write More and Suffer Less. See listing for RSVP or tickets.",
    category: "workshop",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-17/april-davila",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-james-queally-20260818",
    year: 2026,
    monthIndex: 7,
    day: 18,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "James Queally with Tod Goldberg, — Surviving the Lie: A Russell Avery Novel",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents James Queally with Tod Goldberg, — Surviving the Lie: A Russell Avery Novel. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-18/james-queally",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-brian-clune-20260821",
    year: 2026,
    monthIndex: 7,
    day: 21,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Brian Clune — Legends & Lore Along Route 66: Tales from the Mother Road",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Brian Clune — Legends & Lore Along Route 66: Tales from the Mother Road. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-21/brian-clune",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-lisa-johnston-hancock-20260822",
    year: 2026,
    monthIndex: 7,
    day: 22,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Lisa Johnston Hancock reads from & signs Santiago and Great Bear: A Friendship Written in the Stars",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Lisa Johnston Hancock reads from & signs Santiago and Great Bear: A Friendship Written in the Stars. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-22/lisa-johnston-hancock",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-jaime-parker-stickle-20260822",
    year: 2026,
    monthIndex: 7,
    day: 22,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Jaime Parker Stickle — Take Hart: A Thriller (Corey in Los Angeles #2)",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Jaime Parker Stickle — Take Hart: A Thriller (Corey in Los Angeles #2). See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-22/jaime-parker-stickle",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-local-author-day-20260823",
    year: 2026,
    monthIndex: 7,
    day: 23,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Local Author Day Introducing Joe Belk & Dan Joyce",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Local Author Day Introducing Joe Belk & Dan Joyce. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-23/local-author-day",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-diana-giovinnazo-20260825",
    year: 2026,
    monthIndex: 7,
    day: 25,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Diana Giovinnazo with J. Ryan Stradal, — Daughters of Naples",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Diana Giovinnazo with J. Ryan Stradal, — Daughters of Naples. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-25/diana-giovinnazo",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-vromans-fiction-reading-group-20260826",
    year: 2026,
    monthIndex: 7,
    day: 26,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Vroman's Fiction Reading Group",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Vroman's Fiction Reading Group. See listing for RSVP or tickets.",
    category: "other",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-26/vromans-fiction-reading-group",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-yance-wyatt-discusses-20260828",
    year: 2026,
    monthIndex: 7,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Yance Wyatt — The Watersmith",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Yance Wyatt — The Watersmith. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-28/yance-wyatt-discusses",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-linda-liu-20260829",
    year: 2026,
    monthIndex: 7,
    day: 29,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Linda Liu reads from & signs I Guess I’ll Go Eat Worms",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Linda Liu reads from & signs I Guess I’ll Go Eat Worms. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-29/linda-liu",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-sam-quinones-20260831",
    year: 2026,
    monthIndex: 7,
    day: 31,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Sam Quinones — Our Lady of the Angels: The Virgin of Guadalupe on the Walls of Los Angeles",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Sam Quinones — Our Lady of the Angels: The Virgin of Guadalupe on the Walls of Los Angeles. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-08-31/sam-quinones",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-joseph-fink-20260901",
    year: 2026,
    monthIndex: 8,
    day: 1,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Joseph Fink — The Nudge: A Psychological Thriller",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Joseph Fink — The Nudge: A Psychological Thriller. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-01/joseph-fink",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-sonali-kolhatkar-20260903",
    year: 2026,
    monthIndex: 8,
    day: 3,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Sonali Kolhatkar — Breaking Ice: Community Defense Against State Terror and Maga Fascism",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Sonali Kolhatkar — Breaking Ice: Community Defense Against State Terror and Maga Fascism. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-03/sonali-kolhatkar",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-sara-kehaulani-goo-20260904",
    year: 2026,
    monthIndex: 8,
    day: 4,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Sara Kehaulani Goo — Kuleana: A Story of Family, Land, and Legacy in Old Hawai'i",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Sara Kehaulani Goo — Kuleana: A Story of Family, Land, and Legacy in Old Hawai'i. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-04/sara-kehaulani-goo",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-dolph-lundgren-20260917",
    year: 2026,
    monthIndex: 8,
    day: 17,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Dolph Lundgren presents Fights Worth Fighting: Finding Strength in Struggle",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Dolph Lundgren presents Fights Worth Fighting: Finding Strength in Struggle. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Pasadena Presbyterian Church",
    address: "585 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-17/dolph-lundgren",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-penn-cole-20260920",
    year: 2026,
    monthIndex: 8,
    day: 20,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Vroman’s presents Penn Cole with Heidi Cole McAdams, discussing Burn of the Everflame (The Kindred’s Curse Saga #4)",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Vroman’s presents Penn Cole with Heidi Cole McAdams, discussing Burn of the Everflame (The Kindred’s Curse Saga #4). See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-20/penn-cole",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-leigh-bardugo-20260921",
    year: 2026,
    monthIndex: 8,
    day: 21,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Leigh Bardugo with Rebecca Roanhorse, presents Dead Beat",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Leigh Bardugo with Rebecca Roanhorse, presents Dead Beat. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-21/leigh-bardugo",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-vromans-fiction-reading-group-20260923",
    year: 2026,
    monthIndex: 8,
    day: 23,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Vroman's Fiction Reading Group",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Vroman's Fiction Reading Group. See listing for RSVP or tickets.",
    category: "other",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-23/vromans-fiction-reading-group",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans--lee-asher-20260925",
    year: 2026,
    monthIndex: 8,
    day: 25,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Lee Asher signs Saved by the Pack: How 50 Dogs Helped Me Find My Purpose",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Lee Asher signs Saved by the Pack: How 50 Dogs Helped Me Find My Purpose. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-25/-lee-asher",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-local-author-day-20260927",
    year: 2026,
    monthIndex: 8,
    day: 27,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Local Author Day Introducing m.a. Arana, Esma Ali & Paul J. Ramirez",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Local Author Day Introducing m.a. Arana, Esma Ali & Paul J. Ramirez. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-09-27/local-author-day",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-hernan-diaz-20261008",
    year: 2026,
    monthIndex: 9,
    day: 8,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Hernan Diaz discusses Ply",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Hernan Diaz discusses Ply. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Pasadena Presbyterian Church",
    address: "585 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-10-08/hernan-diaz",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-trish-lundy-20261009",
    year: 2026,
    monthIndex: 9,
    day: 9,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Trish Lundy with Veronica Bane, — The Worst is Yet to Come",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Trish Lundy with Veronica Bane, — The Worst is Yet to Come. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-10-09/trish-lundy",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-eric-idle-20261010",
    year: 2026,
    monthIndex: 9,
    day: 10,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Eric Idle discusses Idle in Provence: A Brief History of Thyme",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Eric Idle discusses Idle in Provence: A Brief History of Thyme. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-10-10/eric-idle",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-rebekah-faubion-20261016",
    year: 2026,
    monthIndex: 9,
    day: 16,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Rebekah Faubion with Liz Kerin, — What a Nightmare",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Rebekah Faubion with Liz Kerin, — What a Nightmare. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-10-16/rebekah-faubion",
    sourceChannel: "bookstore",
  },
  {
    id: "la-vromans-ticketed-barbara-kingsolver-20261021",
    year: 2026,
    monthIndex: 9,
    day: 21,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Vroman's Bookstore & The Braille Institute Present: Barbara Kingsolver discussing Partita",
    tagline: "Vroman's Bookstore · Pasadena · Ticketed",
    description: "Vroman's Bookstore presents Vroman's Bookstore & The Braille Institute Present: Barbara Kingsolver discussing Partita. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Vroman's Bookstore",
    venue: "Pasadena Presbyterian Church",
    address: "585 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-10-21/ticketed-barbara-kingsolver",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-vromans-vromans-fiction-reading-group-20261028",
    year: 2026,
    monthIndex: 9,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Vroman's Fiction Reading Group",
    tagline: "Vroman's Bookstore · Pasadena · Author event",
    description: "Vroman's Bookstore presents Vroman's Fiction Reading Group. See listing for RSVP or tickets.",
    category: "other",
    organizer: "Vroman's Bookstore",
    venue: "Vroman's Bookstore",
    address: "695 E Colorado Blvd, Pasadena, CA 91101",
    neighborhood: "Pasadena",
    rsvpUrl: "https://vromansbookstore.com/event/2026-10-28/vromans-fiction-reading-group",
    sourceChannel: "bookstore",
  },
  {
    id: "la-book-soup-dylan-landis-20260701",
    year: 2026,
    monthIndex: 6,
    day: 1,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Dylan Landis with Janet Fitch, — List of All Possible Desires: A Novel in Stories",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Dylan Landis with Janet Fitch, — List of All Possible Desires: A Novel in Stories. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-01/dylan-landis",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-daphne-woolsoncroft-20260707",
    year: 2026,
    monthIndex: 6,
    day: 7,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Daphne Woolsoncroft with Brian Watson, — The Season of Sinking",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Daphne Woolsoncroft with Brian Watson, — The Season of Sinking. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-07/daphne-woolsoncroft",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-brent-simon-20260709",
    year: 2026,
    monthIndex: 6,
    day: 9,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Brent Simon, with Todd Gilchrist, — The Dreamer's Path: Twin Peaks and David Lynch the Actor",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Brent Simon, with Todd Gilchrist, — The Dreamer's Path: Twin Peaks and David Lynch the Actor. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-09/brent-simon",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-jessica-teich-20260710",
    year: 2026,
    monthIndex: 6,
    day: 10,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Jessica Teich with Bourke Floyd, — The Future Tense of Joy: A Memoir",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Jessica Teich with Bourke Floyd, — The Future Tense of Joy: A Memoir. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-10/jessica-teich",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-tad-stoermer-20260711",
    year: 2026,
    monthIndex: 6,
    day: 11,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Tad Stoermer with Joely Fisher, — A Resistance History of the United States",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Tad Stoermer with Joely Fisher, — A Resistance History of the United States. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "Book Soup",
    address: "8818 Sunset Blvd, West Hollywood, CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-11/tad-stoermer",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-talya-jankovits-20260713",
    year: 2026,
    monthIndex: 6,
    day: 13,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Talya Jankovits with Tabby Refael, — The Very Unremarkable Life of Mrs. Etty Bloom",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Talya Jankovits with Tabby Refael, — The Very Unremarkable Life of Mrs. Etty Bloom. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-13/talya-jankovits",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-writers-bloc-presents-brian-tyler-cohen-20260718",
    year: 2026,
    monthIndex: 6,
    day: 18,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Writers Bloc Presents: Brian Tyler Cohen discusses The Day After",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Writers Bloc Presents: Brian Tyler Cohen discusses The Day After. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "JAMS Performing Arts Center 2425 16th St. Santa Monica , CA 90405",
    address: "JAMS Performing Arts Center 2425 16th St. Santa Monica , CA 90405",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-18/writers-bloc-presents-brian-tyler-cohen",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-david-beard-20260720",
    year: 2026,
    monthIndex: 6,
    day: 20,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "David Beard with Dennis Diken, — All Summer Long: Conversations with the Beach Boys from Surf",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents David Beard with Dennis Diken, — All Summer Long: Conversations with the Beach Boys from Surf. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "The Beverly Hills Public Library (Auditorium on Level Two) 444 N. Rexford Drive ",
    address: "The Beverly Hills Public Library (Auditorium on Level Two) 444 N. Rexford Drive Beverly Hills , CA 9",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-20/david-beard",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-cliff-dorfman-20260721",
    year: 2026,
    monthIndex: 6,
    day: 21,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Cliff Dorfman with Seth Green, — Crime Family",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Cliff Dorfman with Seth Green, — Crime Family. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-21/cliff-dorfman",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-andrew-yang-20260722",
    year: 2026,
    monthIndex: 6,
    day: 22,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Andrew Yang with Maddie Connors, — Hey Yang, Where's My Thousand Bucks?: And Other True Stories of S",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Andrew Yang with Maddie Connors, — Hey Yang, Where's My Thousand Bucks?: And Other True Stories of S. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "Beverly Hills Public Library 444 N Rexford Dr Beverly Hills , CA 90210",
    address: "Beverly Hills Public Library 444 N Rexford Dr Beverly Hills , CA 90210",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-22/andrew-yang",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-brad-tolinski-20260723",
    year: 2026,
    monthIndex: 6,
    day: 23,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Brad Tolinski with Michael Walker, — Blow by Blow: The Jeff Beck Story",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Brad Tolinski with Michael Walker, — Blow by Blow: The Jeff Beck Story. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-23/brad-tolinski",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-ticketed-event-annie-jacobsen-conversation-to-20260725",
    year: 2026,
    monthIndex: 6,
    day: 25,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Annie Jacobsen with Tom O'Neill, — Biological War: A Scenario",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Annie Jacobsen with Tom O'Neill, — Biological War: A Scenario. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "Beverly Hills Public Library 444 N. Rexford Dr Beverly Hills , CA 90210",
    address: "Beverly Hills Public Library 444 N. Rexford Dr Beverly Hills , CA 90210",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-25/ticketed-event-annie-jacobsen-conversation-tom-oneill-discusses-signs-biological",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-jesse-malin-20260726",
    year: 2026,
    monthIndex: 6,
    day: 26,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Jesse Malin with author/filmmaker Dito Montiel, — Almost Grown: A New York Memoir",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Jesse Malin with author/filmmaker Dito Montiel, — Almost Grown: A New York Memoir. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-26/jesse-malin",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-bruce-eric-kaplan-discusses-signs-they-went-a-20260728",
    year: 2026,
    monthIndex: 6,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Bruce Eric Kaplan — They Went Another Way: A Hollywood Memoir",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Bruce Eric Kaplan — They Went Another Way: A Hollywood Memoir. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-28/bruce-eric-kaplan-discusses-signs-they-went-another-way-hollywood-memoir",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-unsoupervised-readers-club-20260729",
    year: 2026,
    monthIndex: 6,
    day: 29,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "UNSOUPERVISED READERS CLUB",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents UNSOUPERVISED READERS CLUB. See listing for RSVP or tickets.",
    category: "other",
    organizer: "Book Soup",
    venue: "Book Soup",
    address: "8818 Sunset Blvd, West Hollywood, CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-29/unsoupervised-readers-club",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-sebastian-tillinger-20260730",
    year: 2026,
    monthIndex: 6,
    day: 30,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Sebastian Tillinger with Moon Unit Zappa, — How the Ferris Wheel Was Broken: A Love Letter to Los Angeles",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Sebastian Tillinger with Moon Unit Zappa, — How the Ferris Wheel Was Broken: A Love Letter to Los Angeles. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-30/sebastian-tillinger",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-phil-cousineau-discusses-signs-wisdom-odyssey-20260731",
    year: 2026,
    monthIndex: 6,
    day: 31,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Phil Cousineau — The Wisdom of the Odyssey: Twenty-Four Life Lessons from Homer's Epic",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Phil Cousineau — The Wisdom of the Odyssey: Twenty-Four Life Lessons from Homer's Epic. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-07-31/phil-cousineau-discusses-signs-wisdom-odyssey-twenty-four-life-lessons-homers-epic",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-maria-dilorenzo-20260803",
    year: 2026,
    monthIndex: 7,
    day: 3,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Maria DiLorenzo with Dr. Kris Mohandie, — Confessions of the Green River Killer: A True Story of Manipulati",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Maria DiLorenzo with Dr. Kris Mohandie, — Confessions of the Green River Killer: A True Story of Manipulati. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-03/maria-dilorenzo",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-thomas-mullaney-discusses-signs-how-we-disapp-20260805",
    year: 2026,
    monthIndex: 7,
    day: 5,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Thomas Mullaney — How We Disappear: A Personal History of Information",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Thomas Mullaney — How We Disappear: A Personal History of Information. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-05/thomas-mullaney-discusses-signs-how-we-disappear-personal-history-information",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-david-k-israel-20260807",
    year: 2026,
    monthIndex: 7,
    day: 7,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "David K. Israel with Meghan Daum, — The Lost Mozart",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents David K. Israel with Meghan Daum, — The Lost Mozart. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-07/david-k-israel",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-douglas-messerli-20260808",
    year: 2026,
    monthIndex: 7,
    day: 8,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Douglas Messerli — My Queer Cinema: LGBTQ+ Films Coded and Explicit, Volume One: 1887-1919",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Douglas Messerli — My Queer Cinema: LGBTQ+ Films Coded and Explicit, Volume One: 1887-1919. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-08/douglas-messerli",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-ticketed-eliot-glazer-conversation-justin-tra-20260811",
    year: 2026,
    monthIndex: 7,
    day: 11,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Eliot Glazer with Justin Tranter, — The Terrible, Horrible, No Good, Very Bad Gay: Essays",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Eliot Glazer with Justin Tranter, — The Terrible, Horrible, No Good, Very Bad Gay: Essays. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-11/ticketed-eliot-glazer-conversation-justin-tranter-discusses-signs-terrible",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-alexandra-fleder-conversation-lisa-cheek-disc-20260814",
    year: 2026,
    monthIndex: 7,
    day: 14,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Alexandra Fleder with Lisa Cheek, — Joan of the Arcane",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Alexandra Fleder with Lisa Cheek, — Joan of the Arcane. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-14/alexandra-fleder-conversation-lisa-cheek-discusses-signs-joan-arcane",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-kristen-lopez-discusses-signs-have-you-read-b-20260815",
    year: 2026,
    monthIndex: 7,
    day: 15,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Kristen Lopez — But Have You Read the Book? Romance Edition: 40 Love Stories That Inspired Our Favorite Films",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Kristen Lopez — But Have You Read the Book? Romance Edition: 40 Love Stories That Inspired Our Favorite Films. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-15/kristen-lopez-discusses-signs-have-you-read-book-romance-edition-40-love-stories",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-matthew-hild-discusses-signs-little-more-love-20260817",
    year: 2026,
    monthIndex: 7,
    day: 17,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Matthew Hild — A Little More Love: The Life and Legacy of Olivia Newton-John",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Matthew Hild — A Little More Love: The Life and Legacy of Olivia Newton-John. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-17/matthew-hild-discusses-signs-little-more-love-life-and-legacy-olivia-newton-john",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-ap-thayer-20260818",
    year: 2026,
    monthIndex: 7,
    day: 18,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "A.P. Thayer with Justin Key, — Tapeworm",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents A.P. Thayer with Justin Key, — Tapeworm. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-08-18/ap-thayer",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-rachel-brodsky-conversation-mikael-wood-discu-20260915",
    year: 2026,
    monthIndex: 8,
    day: 15,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Rachel Brodsky with Mikael Wood, — Lessons & Lace: Everything I Know about Dreams, Heartbreak, and Magic I",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Rachel Brodsky with Mikael Wood, — Lessons & Lace: Everything I Know about Dreams, Heartbreak, and Magic I. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-09-15/rachel-brodsky-conversation-mikael-wood-discusses-signs-lessons-lace-everything-i",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-ticketed-event-jeff-garlin-signs-jeff-garlin--20260917",
    year: 2026,
    monthIndex: 8,
    day: 17,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Jeff Garlin signs Jeff Garlin: Best Seat in the House: Moments No One Asked Me to Capture...But I Did Anyway",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Jeff Garlin signs Jeff Garlin: Best Seat in the House: Moments No One Asked Me to Capture...But I Did Anyway. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-09-17/ticketed-event-jeff-garlin-signs-jeff-garlin-best-seat-house-moments-no-one-asked",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-book-soup-presents-david-duchovny-discussing--20260918",
    year: 2026,
    monthIndex: 8,
    day: 18,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "David Duchovny — About Time: Poems Live at Harmony Gold!",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents David Duchovny — About Time: Poems Live at Harmony Gold!. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "Harmony Gold 7655 W. Sunset Blvd Los Angeles , CA 90046",
    address: "Harmony Gold 7655 W. Sunset Blvd Los Angeles , CA 90046",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-09-18/book-soup-presents-david-duchovny-discussing-signing-about-time-poems-live-harmony",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-randee-st-nicholas-discusses-signs-without-an-20260923",
    year: 2026,
    monthIndex: 8,
    day: 23,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Randee St. Nicholas — From Without . . . and from Within: In the Light We Deserve (Photographs 1979-2025)",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Randee St. Nicholas — From Without . . . and from Within: In the Light We Deserve (Photographs 1979-2025). See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-09-23/randee-st-nicholas-discusses-signs-without-and-within-light-we-deserve-photographs",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-lisa-cheek-conversation-samantha-dunn-discuss-20260925",
    year: 2026,
    monthIndex: 8,
    day: 25,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Lisa Cheek with Samantha Dunn, — The Big Day: Saying I Do Only to Discover I Didn't - Another Mostly True M",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Lisa Cheek with Samantha Dunn, — The Big Day: Saying I Do Only to Discover I Didn't - Another Mostly True M. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-09-25/lisa-cheek-conversation-samantha-dunn-discusses-signs-big-day-saying-i-do-only",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-garrison-lovely-discusses-signs-obsolete-ai-i-20260928",
    year: 2026,
    monthIndex: 8,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Garrison Lovely — Obsolete: The AI Industry's Trillion Dollar Race to Replace You--And How to Stop It",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Garrison Lovely — Obsolete: The AI Industry's Trillion Dollar Race to Replace You--And How to Stop It. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-09-28/garrison-lovely-discusses-signs-obsolete-ai-industrys-trillion-dollar-race-replace",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-bobby-finger-lindsey-weber-discuss-i-want-be--20260929",
    year: 2026,
    monthIndex: 8,
    day: 29,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Bobby Finger & Lindsey Weber discuss I Want to Be Famous",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Bobby Finger & Lindsey Weber discuss I Want to Be Famous. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "Harmony Gold 7655 Sunset Blvd West Hollywood , CA 90069",
    address: "Harmony Gold 7655 Sunset Blvd West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-09-29/bobby-finger-lindsey-weber-discuss-i-want-be-famous",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-devon-rodriguez-20260930",
    year: 2026,
    monthIndex: 8,
    day: 30,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Devon Rodriguez presents Work in Progress: A Memoir",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Devon Rodriguez presents Work in Progress: A Memoir. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "First Congregational Church of Los Angeles 540 S. Commonwealth Ave Los Angeles ,",
    address: "First Congregational Church of Los Angeles 540 S. Commonwealth Ave Los Angeles , CA 90020",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-09-30/devon-rodriguez",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-sarah-blakley-cartwright-discusses-signs-heav-20261001",
    year: 2026,
    monthIndex: 9,
    day: 1,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Sarah Blakley-Cartwright — Heavy Cream",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Sarah Blakley-Cartwright — Heavy Cream. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-10-01/sarah-blakley-cartwright-discusses-signs-heavy-cream",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-ellen-oconnell-whittet-discusses-signs-book-h-20261008",
    year: 2026,
    monthIndex: 9,
    day: 8,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Ellen O'Connell Whittet — Book of Hours",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Ellen O'Connell Whittet — Book of Hours. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-10-08/ellen-oconnell-whittet-discusses-signs-book-hours",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "la-book-soup-cal-hoffman-conversation-penelope-miller-disc-20261021",
    year: 2026,
    monthIndex: 9,
    day: 21,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Cal Hoffman with Penelope Miller, — Judah Can't Tell",
    tagline: "Book Soup · West Hollywood · Ticketed",
    description: "Book Soup presents Cal Hoffman with Penelope Miller, — Judah Can't Tell. See listing for RSVP or tickets.",
    category: "reading",
    organizer: "Book Soup",
    venue: "8818 Sunset Boulevard West Hollywood , CA 90069",
    address: "8818 Sunset Boulevard West Hollywood , CA 90069",
    neighborhood: "West Hollywood",
    rsvpUrl: "https://booksoup.com/event/2026-10-21/cal-hoffman-conversation-penelope-miller-discusses-signs-judah-cant-tell",
    sourceChannel: "bookstore",
    price: "paid",
  },
];

function mapSpec(spec: CuratedSpec): WorkshopEvent {
  const start = DateTime.fromObject(
    {
      year: spec.year,
      month: spec.monthIndex + 1,
      day: spec.day,
      hour: spec.hour,
      minute: spec.minute,
      second: 0,
      millisecond: 0,
    },
    { zone: spec.timeZone },
  );
  const end =
    spec.endHour != null
      ? DateTime.fromObject(
          {
            year: spec.year,
            month: spec.monthIndex + 1,
            day: spec.day,
            hour: spec.endHour,
            minute: spec.endMinute ?? 0,
            second: 0,
            millisecond: 0,
          },
          { zone: spec.timeZone },
        )
      : start.plus({ hours: 1 });

  return {
    id: spec.id,
    cityId: "la",
    title: spec.title,
    tagline: spec.tagline,
    description: spec.description,
    start: start.toISO()!,
    end: end.toISO()!,
    timeZone: spec.timeZone,
    format: "in_person",
    price: spec.price ?? "unknown",
    category: spec.category,
    organizer: spec.organizer,
    venue: spec.venue,
    address: spec.address,
    neighborhood: spec.neighborhood,
    rsvpUrl: spec.rsvpUrl,
    source: "LA curated (Vroman's, Book Soup)",
    sourceChannel: spec.sourceChannel,
    listingProvenance: "live",
  };
}

export type CuratedMeta = {
  curatedTotal: number;
  rowsInMonth: number;
};

export function fetchLaCuratedEventsForMonth(
  year: number,
  monthIndex: number,
): { events: WorkshopEvent[]; meta: CuratedMeta } {
  const rows = CURATED.filter(
    (s) => s.year === year && s.monthIndex === monthIndex,
  );
  return {
    events: rows.map(mapSpec),
    meta: { curatedTotal: CURATED.length, rowsInMonth: rows.length },
  };
}
