import { DateTime } from "luxon";
import type {
  WorkshopEvent,
  WorkshopEventCategory,
} from "@/lib/workshop-types";

/** Omaha and Lincoln are both Central Time. */
const TZ = "America/Chicago";

const BOOKWORM_ADDRESS = "2501 South 90th Street Suite 111, Omaha, NE 68124";
const FRANCIE_ADDRESS = "130 S. 13th Street, Lincoln, NE 68508";
const LARKSONG_ADDRESS = "1600 N. Cotner Blvd, Lincoln, NE 68505";
const LOCAL_ART_PLUG_ADDRESS = "1722 St. Marys Ave Suite 110, Omaha, NE 68102";
const BENSON_BRANCH_ADDRESS = "6015 Binney Street, Omaha, NE 68104";
const CENTRAL_LIBRARY_ADDRESS = "7205 Dodge St, Omaha, NE 68114";
const ELKHORN_BRANCH_ADDRESS = "2100 Reading Plz, Elkhorn, NE 68022";
const SWANSON_BRANCH_ADDRESS = "9101 W Dodge Rd, Omaha, NE 68114";

type CuratedSpec = {
  id: string;
  year: number;
  monthIndex: number;
  day: number;
  hour: number;
  minute: number;
  endHour?: number;
  endMinute?: number;
  timeZone: string;
  title: string;
  tagline: string;
  description: string;
  category: WorkshopEventCategory;
  organizer: string;
  venue: string;
  address: string;
  neighborhood: string;
  rsvpUrl?: string;
  rsvpIsGeneralCalendar?: boolean;
  sourceChannel: WorkshopEvent["sourceChannel"];
  price?: WorkshopEvent["price"];
};

const CURATED: CuratedSpec[] = [
  // ── The Bookworm (Omaha) ──────────────────────────────────────────
  {
    id: "ne-bookworm-nora-barth-time-warden-20260725",
    year: 2026,
    monthIndex: 6,
    day: 25,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 30,
    timeZone: TZ,
    title: 'Nora Barth — The Time Warden',
    tagline: "The Bookworm · Omaha · Free · Signing & discussion",
    description:
      "Local author Nora Barth signs and discusses her debut novel The Time Warden — a story of a boy in a helmet, a girl in a mask, and one fateful night that turns them into each other's worst enemies.",
    category: "reading",
    organizer: "The Bookworm",
    venue: "The Bookworm",
    address: BOOKWORM_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://bookwormomaha.com/event/2026-07-25/nora-barth-will-sign-discuss-time-warden",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-bookworm-ashten-arkfeld-anxious-ashten-20260802",
    year: 2026,
    monthIndex: 7,
    day: 2,
    hour: 11,
    minute: 0,
    endHour: 12,
    endMinute: 0,
    timeZone: TZ,
    title: 'Ashten Arkfeld — Anxious Ashten',
    tagline: "The Bookworm · Omaha · Children's · Free",
    description:
      "Ashten Arkfeld reads and signs Anxious Ashten: A Child's Perspective on Anxiety — a picture-book look at childhood anxiety for young readers and families.",
    category: "reading",
    organizer: "The Bookworm",
    venue: "The Bookworm",
    address: BOOKWORM_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://bookwormomaha.com/event/2026-08-02/ashten-arkfeld-will-sign-anxious-ashten",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-bookworm-colleen-morton-busch-smolder-20260805",
    year: 2026,
    monthIndex: 7,
    day: 5,
    hour: 18,
    minute: 0,
    endHour: 19,
    endMinute: 30,
    timeZone: TZ,
    title: 'Colleen Morton Busch — Smolder (with Shyla Shehan)',
    tagline: "The Bookworm · Omaha · Poetry · Free",
    description:
      "Colleen Morton Busch reads from Smolder, winner of the 2025 Richard-Gabriel Rummonds Poetry Prize, exploring the many kinds of fire blazing inside a life. Omaha poet Shyla Shehan (Mining the Gap) reads as well.",
    category: "reading",
    organizer: "The Bookworm",
    venue: "The Bookworm",
    address: BOOKWORM_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://bookwormomaha.com/event/2026-08-05/colleen-morton-busch-will-sign-smolder",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-bookworm-tipler-christiansen-luigi-20260816",
    year: 2026,
    monthIndex: 7,
    day: 16,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 30,
    timeZone: TZ,
    title: 'Doyle Tipler & Erich Christiansen — The History of Luigi Inc.',
    tagline: "The Bookworm · Omaha · Free · Signing",
    description:
      "Doyle Tipler and Erich Christiansen sign The History of Luigi Inc. at The Bookworm.",
    category: "reading",
    organizer: "The Bookworm",
    venue: "The Bookworm",
    address: BOOKWORM_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://bookwormomaha.com/event/2026-08-16/doyle-tipler-erich-christiansen-will-sign-history-luigi-inc",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-bookworm-ariel-lawhon-pirate-queen-20260912",
    year: 2026,
    monthIndex: 8,
    day: 12,
    hour: 18,
    minute: 0,
    endHour: 20,
    endMinute: 0,
    timeZone: TZ,
    title: "Ariel Lawhon — The Pirate Queen",
    tagline: "The Bookworm · Omaha Scottish Rite · Ticketed",
    description:
      "The Bookworm presents an evening with New York Times bestselling author Ariel Lawhon for her new novel The Pirate Queen at the Omaha Scottish Rite. General admission ($39) via Eventbrite includes one copy of the book and admission for one person.",
    category: "reading",
    organizer: "The Bookworm",
    venue: "The Omaha Scottish Rite",
    address: "202 S. 20th Street, Omaha, NE 68102",
    neighborhood: "Omaha",
    rsvpUrl:
      "https://bookwormomaha.com/event/2026-09-12/evening-ariel-lawhon-ticketed-event",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "ne-bookworm-william-kent-krueger-gods-country-20261003",
    year: 2026,
    monthIndex: 9,
    day: 3,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 30,
    timeZone: TZ,
    title: "William Kent Krueger — God's Country",
    tagline: "The Bookworm · Omaha · Free · Signing",
    description:
      "William Kent Krueger discusses and signs God's Country, book #22 in the Cork O'Connor mystery series — an action-packed return to Omaha for the Edgar Award–winning author of Ordinary Grace and This Tender Land.",
    category: "reading",
    organizer: "The Bookworm",
    venue: "The Bookworm",
    address: BOOKWORM_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://bookwormomaha.com/event/2026-10-03/william-kent-krueger-will-sign-gods-country",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-bookworm-ml-rio-hot-wax-20261014",
    year: 2026,
    monthIndex: 9,
    day: 14,
    hour: 18,
    minute: 0,
    endHour: 19,
    endMinute: 30,
    timeZone: TZ,
    title: 'M.L. Rio — Hot Wax',
    tagline: "The Bookworm · Omaha · Free · Signing",
    description:
      "M.L. Rio — author of If We Were Villains — signs Hot Wax at The Bookworm.",
    category: "reading",
    organizer: "The Bookworm",
    venue: "The Bookworm",
    address: BOOKWORM_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl: "https://bookwormomaha.com/event/2026-10-14/ml-rio-will-sign-hot-wax",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-bookworm-mary-pipher-letters-20261020",
    year: 2026,
    monthIndex: 9,
    day: 20,
    hour: 18,
    minute: 0,
    endHour: 19,
    endMinute: 30,
    timeZone: TZ,
    title: 'Mary Pipher — Letters to a Young Therapist',
    tagline: "The Bookworm · Omaha · Free · Signing",
    description:
      "Nebraska psychologist and bestselling author Mary Pipher (Reviving Ophelia, Women Rowing North) signs Letters to a Young Therapist at The Bookworm.",
    category: "reading",
    organizer: "The Bookworm",
    venue: "The Bookworm",
    address: BOOKWORM_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://bookwormomaha.com/event/2026-10-20/mary-pipher-will-sign-letters-young-therapist",
    sourceChannel: "bookstore",
    price: "free",
  },

  // ── Francie & Finch (Lincoln) ─────────────────────────────────────
  {
    id: "ne-francie-alena-bruzas-broken-edge-20260718",
    year: 2026,
    monthIndex: 6,
    day: 18,
    hour: 16,
    minute: 30,
    endHour: 17,
    endMinute: 30,
    timeZone: TZ,
    title: "Alena Bruzas — The Broken Edge of the World (with Allison Bitz)",
    tagline: "Francie & Finch · Lincoln · Book launch · Free",
    description:
      "Francie & Finch celebrates the launch of Alena Bruzas's third novel, The Broken Edge of the World, in conversation with local author Allison Bitz. Bruzas grew up in Seattle and lives in Lincoln; she is also the author of To the Bone and Ever Since.",
    category: "reading",
    organizer: "Francie & Finch Bookshop",
    venue: "Francie & Finch Bookshop",
    address: FRANCIE_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl:
      "https://francieandfinch.com/event/book-launch-alena-bruzas-the-broken-edge-of-the-world/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-francie-colleen-morton-busch-smolder-20260807",
    year: 2026,
    monthIndex: 7,
    day: 7,
    hour: 16,
    minute: 30,
    endHour: 17,
    endMinute: 30,
    timeZone: TZ,
    title: "Colleen Morton Busch — Smolder (with Judy Lorenzen)",
    tagline: "Francie & Finch · Lincoln · Poetry · Free",
    description:
      "Ex Ophidia's 2025 Richard-Gabriel Rummonds Poetry Prize winner Colleen Morton Busch presents Smolder in conversation with Nebraska poet Judy Lorenzen.",
    category: "reading",
    organizer: "Francie & Finch Bookshop",
    venue: "Francie & Finch Bookshop",
    address: FRANCIE_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl:
      "https://francieandfinch.com/event/visiting-author-colleen-morton-busch-in-conversation-with-judy-lorenzen-smolder/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-francie-david-moscovich-premieres-20260810",
    year: 2026,
    monthIndex: 7,
    day: 10,
    hour: 17,
    minute: 30,
    endHour: 18,
    endMinute: 30,
    timeZone: TZ,
    title: "David Moscovich — Premieres: A Memoir in Verse",
    tagline: "Francie & Finch · Lincoln · Book launch · Free",
    description:
      "Francie & Finch hosts the book launch for David Moscovich's Premieres: A Memoir in Verse.",
    category: "reading",
    organizer: "Francie & Finch Bookshop",
    venue: "Francie & Finch Bookshop",
    address: FRANCIE_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl:
      "https://francieandfinch.com/event/visiting-author-david-moscovich-premieres-a-memoir-in-verse/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-francie-matt-schur-holy-ground-20260815",
    year: 2026,
    monthIndex: 7,
    day: 15,
    hour: 16,
    minute: 30,
    endHour: 17,
    endMinute: 30,
    timeZone: TZ,
    title: "Matt Schur — Even This is Holy Ground: Poetry",
    tagline: "Francie & Finch · Lincoln · Poetry launch · Free",
    description:
      "Book launch for Matt Schur's poetry collection Even This is Holy Ground at Francie & Finch Bookshop.",
    category: "reading",
    organizer: "Francie & Finch Bookshop",
    venue: "Francie & Finch Bookshop",
    address: FRANCIE_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl:
      "https://francieandfinch.com/event/book-launch-matt-schur-even-this-is-holy-ground-poetry/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-francie-marlene-zuk-outsider-animals-20260818",
    year: 2026,
    monthIndex: 7,
    day: 18,
    hour: 17,
    minute: 30,
    endHour: 18,
    endMinute: 30,
    timeZone: TZ,
    title: "Marlene Zuk — Outsider Animals",
    tagline: "Francie & Finch · Lincoln · Free",
    description:
      "Visiting author Marlene Zuk discusses Outsider Animals: How the Creatures at the Margins of Our Lives Have the Most to Teach Us.",
    category: "reading",
    organizer: "Francie & Finch Bookshop",
    venue: "Francie & Finch Bookshop",
    address: FRANCIE_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl:
      "https://francieandfinch.com/event/visiting-author-marlene-zuk-outsider-animals/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "ne-francie-alexandra-hayne-what-ruth-learned-20260829",
    year: 2026,
    monthIndex: 7,
    day: 29,
    hour: 16,
    minute: 30,
    endHour: 17,
    endMinute: 30,
    timeZone: TZ,
    title: "Alexandra Hayne — What Ruth Learned",
    tagline: "Francie & Finch · Lincoln · Free",
    description:
      "Visiting author Alexandra Hayne presents What Ruth Learned at Francie & Finch Bookshop.",
    category: "reading",
    organizer: "Francie & Finch Bookshop",
    venue: "Francie & Finch Bookshop",
    address: FRANCIE_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl:
      "https://francieandfinch.com/event/visiting-author-alexandra-hayne-what-ruth-learned/",
    sourceChannel: "bookstore",
    price: "free",
  },

  // ── Nebraska Writers Collective ───────────────────────────────────
  {
    id: "ne-nwc-shelby-martinez-workshop-20260721",
    year: 2026,
    monthIndex: 6,
    day: 21,
    hour: 17,
    minute: 30,
    endHour: 19,
    endMinute: 30,
    timeZone: TZ,
    title: "Writers Workshop w/ Shelby Martinez — Genealogy",
    tagline: "Nebraska Writers Collective · OPL Central · Free",
    description:
      "Nebraska Writers Collective writers workshop with Shelby Martinez at Omaha Public Library's Central Library (Genealogy and Local History Room). Theme: Genealogy.",
    category: "workshop",
    organizer: "Nebraska Writers Collective",
    venue: "Omaha Public Library — Central Library",
    address: CENTRAL_LIBRARY_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl: "https://www.newriters.org/events/writers-workshop-wshelby-martinez",
    sourceChannel: "literary_org",
    price: "free",
  },
  {
    id: "ne-nwc-shelly-nosbisch-workshop-20260722",
    year: 2026,
    monthIndex: 6,
    day: 22,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 30,
    timeZone: TZ,
    title: "Writers' Workshop w/ Shelly Nosbisch — Heroes vs Villains",
    tagline: "Nebraska Writers Collective · Benson Branch · Free",
    description:
      "Nebraska Writers Collective workshop with Shelly Nosbisch at OPL's Benson Branch. Theme: Heroes vs Villains.",
    category: "workshop",
    organizer: "Nebraska Writers Collective",
    venue: "Omaha Public Library — Benson Branch",
    address: BENSON_BRANCH_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl: "https://www.newriters.org/events/writers-workshop-wshelly-nosbisch",
    sourceChannel: "literary_org",
    price: "free",
  },
  {
    id: "ne-nwc-riley-westerholt-workshop-20260807",
    year: 2026,
    monthIndex: 7,
    day: 7,
    hour: 10,
    minute: 0,
    endHour: 12,
    endMinute: 0,
    timeZone: TZ,
    title: "Writers Workshop w/ Riley Westerholt — Mysteries",
    tagline: "Nebraska Writers Collective · OPL Central · Free",
    description:
      "Nebraska Writers Collective writers workshop with Riley Westerholt at Omaha Central Library. Theme: Mysteries.",
    category: "workshop",
    organizer: "Nebraska Writers Collective",
    venue: "Omaha Public Library — Central Library",
    address: CENTRAL_LIBRARY_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://www.newriters.org/events/writers-workshop-wriley-westerholt-1",
    sourceChannel: "literary_org",
    price: "free",
  },
  {
    id: "ne-nwc-omaha-poetry-slam-20260808",
    year: 2026,
    monthIndex: 7,
    day: 8,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "Omaha Poetry Slam",
    tagline: "Nebraska Writers Collective · Local Art Plug · $10 suggested",
    description:
      "Monthly open mic and competitive poetry slam, second Saturday of the month. Doors 6:30 PM; open mic then individual slam. Sign up at the event (bring three poems to compete). $10 suggested donation; top scorer wins $50.",
    category: "open-mic",
    organizer: "Nebraska Writers Collective",
    venue: "The Local Art Plug",
    address: LOCAL_ART_PLUG_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl: "https://www.newriters.org/events/omaha-poetry-slam-5",
    sourceChannel: "literary_org",
    price: "paid",
  },
  {
    id: "ne-nwc-lincoln-poetry-slam-20260813",
    year: 2026,
    monthIndex: 7,
    day: 13,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "Lincoln Poetry Slam",
    tagline: "Nebraska Writers Collective · Larksong · $10 suggested",
    description:
      "Monthly open mic and competitive poetry slam, second Thursday of the month at Larksong Writers Place. Doors 6:30 PM. Sign up at the event. $10 suggested donation.",
    category: "open-mic",
    organizer: "Nebraska Writers Collective",
    venue: "Larksong Writers Place",
    address: LARKSONG_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl: "https://www.newriters.org/events/lincoln-poetry-slam-1",
    sourceChannel: "literary_org",
    price: "paid",
  },
  {
    id: "ne-nwc-allana-pommier-workshop-20260829",
    year: 2026,
    monthIndex: 7,
    day: 29,
    hour: 14,
    minute: 0,
    endHour: 16,
    endMinute: 0,
    timeZone: TZ,
    title: "Writers Workshop w/ Allana Pommier — Science Fiction",
    tagline: "Nebraska Writers Collective · Benson Branch · Free",
    description:
      "Nebraska Writers Collective workshop with Allana Pommier at OPL's Benson Branch. Theme: Science Fiction.",
    category: "workshop",
    organizer: "Nebraska Writers Collective",
    venue: "Omaha Public Library — Benson Branch",
    address: BENSON_BRANCH_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl: "https://www.newriters.org/events/writers-workshop-w",
    sourceChannel: "literary_org",
    price: "free",
  },
  {
    id: "ne-nwc-lincoln-poetry-slam-20260910",
    year: 2026,
    monthIndex: 8,
    day: 10,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "Lincoln Poetry Slam",
    tagline: "Nebraska Writers Collective · Larksong · $10 suggested",
    description:
      "Monthly open mic and competitive poetry slam at Larksong Writers Place (second Thursday). Doors 6:30 PM; open mic then slam. $10 suggested donation.",
    category: "open-mic",
    organizer: "Nebraska Writers Collective",
    venue: "Larksong Writers Place",
    address: LARKSONG_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl: "https://www.newriters.org/events/lincoln-poetry-slam-1",
    sourceChannel: "literary_org",
    price: "paid",
  },
  {
    id: "ne-nwc-kids-workshop-shelby-nosbisch-20260912",
    year: 2026,
    monthIndex: 8,
    day: 12,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 30,
    timeZone: TZ,
    title: "Writer's Workshop for Kids with Shelby Nosbisch",
    tagline: "Nebraska Writers Collective · Free · Ages youth",
    description:
      "Nebraska Writers Collective kids writing workshop with Shelby Nosbisch. See listing for location details.",
    category: "workshop",
    organizer: "Nebraska Writers Collective",
    venue: "See event listing",
    address: "Omaha, NE",
    neighborhood: "Omaha",
    rsvpUrl:
      "https://www.newriters.org/events/writers-workshop-for-kids-with-shelby-nosbisch",
    sourceChannel: "literary_org",
    price: "free",
  },
  {
    id: "ne-nwc-omaha-poetry-slam-20260912",
    year: 2026,
    monthIndex: 8,
    day: 12,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "Omaha Poetry Slam",
    tagline: "Nebraska Writers Collective · Local Art Plug · $10 suggested",
    description:
      "Monthly open mic and competitive poetry slam at The Local Art Plug (second Saturday). Doors 6:30 PM. $10 suggested donation; top scorer wins $50.",
    category: "open-mic",
    organizer: "Nebraska Writers Collective",
    venue: "The Local Art Plug",
    address: LOCAL_ART_PLUG_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl: "https://www.newriters.org/events",
    rsvpIsGeneralCalendar: true,
    sourceChannel: "literary_org",
    price: "paid",
  },
  {
    id: "ne-nwc-lincoln-poetry-slam-20261008",
    year: 2026,
    monthIndex: 9,
    day: 8,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "Lincoln Poetry Slam",
    tagline: "Nebraska Writers Collective · Larksong · $10 suggested",
    description:
      "Monthly open mic and competitive poetry slam at Larksong Writers Place (second Thursday). Doors 6:30 PM. $10 suggested donation.",
    category: "open-mic",
    organizer: "Nebraska Writers Collective",
    venue: "Larksong Writers Place",
    address: LARKSONG_ADDRESS,
    neighborhood: "Lincoln",
    rsvpUrl: "https://www.newriters.org/events/lincoln-poetry-slam-1",
    sourceChannel: "literary_org",
    price: "paid",
  },
  {
    id: "ne-nwc-omaha-poetry-slam-20261010",
    year: 2026,
    monthIndex: 9,
    day: 10,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "Omaha Poetry Slam",
    tagline: "Nebraska Writers Collective · Local Art Plug · $10 suggested",
    description:
      "Monthly open mic and competitive poetry slam at The Local Art Plug (second Saturday). Doors 6:30 PM. $10 suggested donation.",
    category: "open-mic",
    organizer: "Nebraska Writers Collective",
    venue: "The Local Art Plug",
    address: LOCAL_ART_PLUG_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl: "https://www.newriters.org/events",
    rsvpIsGeneralCalendar: true,
    sourceChannel: "literary_org",
    price: "paid",
  },

  // ── Omaha Public Library book clubs ───────────────────────────────
  {
    id: "ne-opl-reading-challenge-book-club-20260912",
    year: 2026,
    monthIndex: 8,
    day: 12,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 0,
    timeZone: TZ,
    title: "Reading Challenge Book Club",
    tagline: "Omaha Public Library · Swanson Branch · Free",
    description:
      "Join OPL on the second Saturday for a lively discussion of this month's featured title tied to the OPL Reading Challenge. Limited copies available at W. Clarke Swanson Branch.",
    category: "other",
    organizer: "Omaha Public Library",
    venue: "W. Clarke Swanson Branch",
    address: SWANSON_BRANCH_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://omaha.bibliocommons.com/v2/events?series=693726ad7ed7c62f00a96a3c",
    sourceChannel: "library",
    price: "free",
  },
  {
    id: "ne-opl-lets-get-literary-20260928",
    year: 2026,
    monthIndex: 8,
    day: 28,
    hour: 18,
    minute: 30,
    endHour: 19,
    endMinute: 30,
    timeZone: TZ,
    title: "Let's Get Lit-erary Book Club",
    tagline: "Omaha Public Library · Elkhorn Branch · Free",
    description:
      "Join OPL on the fourth Monday for a lively discussion of this month's featured book at Bess Johnson Elkhorn Branch. Limited copies available at the branch.",
    category: "other",
    organizer: "Omaha Public Library",
    venue: "Bess Johnson Elkhorn Branch",
    address: ELKHORN_BRANCH_ADDRESS,
    neighborhood: "Elkhorn",
    rsvpUrl:
      "https://omaha.bibliocommons.com/v2/events?series=68bf424be56ab2b832a70f08",
    sourceChannel: "library",
    price: "free",
  },
  {
    id: "ne-opl-reading-challenge-book-club-20261010",
    year: 2026,
    monthIndex: 9,
    day: 10,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 0,
    timeZone: TZ,
    title: "Reading Challenge Book Club",
    tagline: "Omaha Public Library · Swanson Branch · Free",
    description:
      "Second-Saturday book club for OPL's Reading Challenge titles at W. Clarke Swanson Branch.",
    category: "other",
    organizer: "Omaha Public Library",
    venue: "W. Clarke Swanson Branch",
    address: SWANSON_BRANCH_ADDRESS,
    neighborhood: "Omaha",
    rsvpUrl:
      "https://omaha.bibliocommons.com/v2/events?series=693726ad7ed7c62f00a96a3c",
    sourceChannel: "library",
    price: "free",
  },
  {
    id: "ne-opl-lets-get-literary-20261026",
    year: 2026,
    monthIndex: 9,
    day: 26,
    hour: 18,
    minute: 30,
    endHour: 19,
    endMinute: 30,
    timeZone: TZ,
    title: "Let's Get Lit-erary Book Club",
    tagline: "Omaha Public Library · Elkhorn Branch · Free",
    description:
      "Fourth-Monday book club at Bess Johnson Elkhorn Branch. See OPL for this month's title and holds.",
    category: "other",
    organizer: "Omaha Public Library",
    venue: "Bess Johnson Elkhorn Branch",
    address: ELKHORN_BRANCH_ADDRESS,
    neighborhood: "Elkhorn",
    rsvpUrl:
      "https://omaha.bibliocommons.com/v2/events?series=68bf424be56ab2b832a70f08",
    sourceChannel: "library",
    price: "free",
  },

  // ── Community / bookstore trail ───────────────────────────────────
  {
    id: "ne-novel-idea-book-trail-20260930",
    year: 2026,
    monthIndex: 8,
    day: 30,
    hour: 10,
    minute: 0,
    endHour: 17,
    endMinute: 0,
    timeZone: TZ,
    title: "Nebraska Book Trail — Passport Deadline",
    tagline: "A Novel Idea & statewide indies · Through Sept 30",
    description:
      "Explore 20+ independent bookstores across Nebraska on the Nebraska Book Trail. Pick up a passport at any participating shop (including A Novel Idea and Francie & Finch in Lincoln) and collect stamps through September 30, 2026.",
    category: "other",
    organizer: "A Novel Idea Bookstore",
    venue: "A Novel Idea Bookstore",
    address: "118 N 14th St, Lincoln, NE 68508",
    neighborhood: "Lincoln",
    rsvpUrl: "https://anovelideabookstore.com/events-calendars/",
    rsvpIsGeneralCalendar: true,
    sourceChannel: "bookstore",
    price: "free",
  },
];

function mapSpec(spec: CuratedSpec): WorkshopEvent {
  const start = DateTime.fromObject(
    {
      year: spec.year,
      month: spec.monthIndex + 1,
      day: spec.day,
      hour: spec.hour,
      minute: spec.minute,
      second: 0,
      millisecond: 0,
    },
    { zone: spec.timeZone },
  );
  const end =
    spec.endHour != null
      ? DateTime.fromObject(
          {
            year: spec.year,
            month: spec.monthIndex + 1,
            day: spec.day,
            hour: spec.endHour,
            minute: spec.endMinute ?? 0,
            second: 0,
            millisecond: 0,
          },
          { zone: spec.timeZone },
        )
      : start.plus({ hours: 1 });

  return {
    id: spec.id,
    cityId: "ne",
    title: spec.title,
    tagline: spec.tagline,
    description: spec.description,
    start: start.toISO()!,
    end: end.toISO()!,
    timeZone: spec.timeZone,
    format: "in-person",
    price: spec.price ?? "unknown",
    category: spec.category,
    organizer: spec.organizer,
    venue: spec.venue,
    address: spec.address,
    neighborhood: spec.neighborhood,
    rsvpUrl: spec.rsvpUrl,
    rsvpIsGeneralCalendar: spec.rsvpIsGeneralCalendar,
    source: "Omaha / Lincoln curated listings",
    sourceChannel: spec.sourceChannel,
    listingProvenance: "live",
  };
}

export type NebraskaCuratedMeta = {
  curatedTotal: number;
  rowsInMonth: number;
};

export function fetchNebraskaCuratedEventsForMonth(
  year: number,
  monthIndex: number,
): { events: WorkshopEvent[]; meta: NebraskaCuratedMeta } {
  const rows = CURATED.filter(
    (s) => s.year === year && s.monthIndex === monthIndex,
  );
  return {
    events: rows.map(mapSpec),
    meta: { curatedTotal: CURATED.length, rowsInMonth: rows.length },
  };
}
