import { DateTime } from "luxon";
import type { WorkshopEvent } from "@/lib/workshop-types";

const TZ = "America/Los_Angeles";
const SDPL_CAL =
  "https://sandiego.events.mylibrary.digital/";

type CuratedSpec = {
  id: string;
  year: number;
  monthIndex: number;
  day: number;
  hour: number;
  minute?: number;
  endHour?: number;
  endMinute?: number;
  title: string;
  tagline: string;
  description: string;
  category: WorkshopEvent["category"];
  organizer: string;
  venue: string;
  address?: string;
  neighborhood?: string;
  format?: WorkshopEvent["format"];
  virtualLabel?: string;
  rsvpUrl?: string;
  rsvpIsGeneralCalendar?: boolean;
  price?: WorkshopEvent["price"];
  priceDetail?: string;
  registrationRequired?: boolean;
  sourceChannel?: WorkshopEvent["sourceChannel"];
  source?: string;
};

/**
 * Curated San Diego literary events (SDPL book clubs / workshops / author talks
 * plus selected open mics). Times are Pacific unless noted.
 * August is capped at 15 literary listings.
 */
const EVENTS: CuratedSpec[] = [
  // —— August 2026 (≤15) ——
  {
    id: "sd-sdwi-wednesday-evening-book-club-20260805",
    year: 2026,
    monthIndex: 7,
    day: 5,
    hour: 18,
    minute: 0,
    endHour: 19,
    endMinute: 0,
    title: "Wednesday Evening Book Club with Rebecca Li",
    tagline: "San Diego Writers, Ink · Zoom · Laufey's Book Club · $15",
    description:
      "Laufey's Book Club with Rebecca Li—discuss one of Laufey's picks (typically fiction with a whimsical bent), identify craft elements you love, and talk about using them in your own writing. Meets once every two months on Zoom. This session: Interpreter of Maladies by Jhumpa Lahiri. $15 for members and nonmembers. Zoom link emailed 24 hours before class.",
    category: "reading",
    organizer: "San Diego Writers, Ink",
    venue: "Zoom (Live)",
    format: "virtual",
    virtualLabel: "Zoom (link emailed 24 hours before class)",
    rsvpUrl: "https://secure.writeyourstorynow.org/eventReg.jsp?event=25556",
    price: "paid",
    priceDetail: "$15",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdpl-gay-mens-book-club-20260804",
    year: 2026,
    monthIndex: 7,
    day: 4,
    hour: 18,
    minute: 0,
    endHour: 19,
    endMinute: 30,
    title: "Gay Men's Book Club",
    tagline: "Mission Hills-Hillcrest/Knox Library · Book discussion",
    description:
      "Adult book discussion focused on literature at Mission Hills-Hillcrest/Knox Library. Part of San Diego Public Library's ongoing book club series.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Mission Hills-Hillcrest/Knox Library",
    neighborhood: "Mission Hills / Hillcrest",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdpl-off-beat-book-club-20260804",
    year: 2026,
    monthIndex: 7,
    day: 4,
    hour: 18,
    minute: 30,
    endHour: 20,
    endMinute: 0,
    title: "Off-Beat Book Club",
    tagline: "Ocean Beach Library · Book discussion",
    description:
      "Adult book discussion focused on literature at Ocean Beach Library. Part of San Diego Public Library's ongoing book club series.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Ocean Beach Library",
    neighborhood: "Ocean Beach",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdpl-write-your-heart-out-20260806",
    year: 2026,
    monthIndex: 7,
    day: 6,
    hour: 10,
    minute: 0,
    endHour: 12,
    endMinute: 0,
    title: "Write Your Heart Out: Writing Practice",
    tagline: "Mission Hills-Hillcrest/Knox Library · Writing workshop",
    description:
      "A literature-focused writing practice workshop for adults, emerging adults, and older adults at Mission Hills-Hillcrest/Knox Library.",
    category: "workshop",
    organizer: "San Diego Public Library",
    venue: "Mission Hills-Hillcrest/Knox Library",
    neighborhood: "Mission Hills / Hillcrest",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdpl-fiction-lovers-book-club-20260808",
    year: 2026,
    monthIndex: 7,
    day: 8,
    hour: 10,
    minute: 0,
    endHour: 11,
    endMinute: 30,
    title: "Fiction Lovers Book Club",
    tagline: "North University Community Library · Book discussion",
    description:
      "Adult book discussion for fiction lovers at North University Community Library.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "North University Community Library",
    neighborhood: "University City",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdpl-sci-fi-book-club-20260811",
    year: 2026,
    monthIndex: 7,
    day: 11,
    hour: 18,
    minute: 0,
    endHour: 19,
    endMinute: 30,
    title: "Sci-Fi Book Club",
    tagline: "Kensington-Normal Heights Library · Book discussion",
    description:
      "Literature-focused science fiction book discussion at Kensington-Normal Heights Library.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Kensington-Normal Heights Library",
    neighborhood: "Kensington / Normal Heights",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdwi-sneaking-backdoor-poetry-prose-20260811",
    year: 2026,
    monthIndex: 7,
    day: 11,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 30,
    title: "Sneaking in the Backdoor of Poetry and Prose with Jill Badonsky",
    tagline: "San Diego Writers, Ink · Zoom · Session 1 of 3",
    description:
      "Low-pressure three-week Zoom workshop with Jill Badonsky. Prompts that begin with lists, mind-mapping, and images make writing poetry easier and the Muse more cooperative—transcribe poems and prose lurking under scattered minds. Learn tricks from poet laureates Billy Collins and Joy Harjo. For anyone who loves words, intimidated beginners, or seasoned writers craving new ideas. Sessions: Tuesdays August 11, 18 & 25, 2:00–3:30 PM PT. Zoom link emailed 24 hours before class. $81 members · $94.50 nonmembers.",
    category: "workshop",
    organizer: "San Diego Writers, Ink",
    venue: "Zoom (Live)",
    format: "virtual",
    virtualLabel: "Zoom (link emailed 24 hours before class)",
    rsvpUrl:
      "https://writeyourstorynow.org/classes-workshops/2026-08-11-sneaking-in-the-backdoor-of-poetry-and-prose-with-jill-badonsky/",
    price: "paid",
    priceDetail: "$81 members · $94.50 nonmembers",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdwi-creating-emotion-judy-reeves-20260812",
    year: 2026,
    monthIndex: 7,
    day: 12,
    hour: 18,
    minute: 30,
    endHour: 20,
    endMinute: 30,
    title: "Creating Emotion on the Page: Atmosphere and Mood with Judy Reeves",
    tagline: "San Diego Writers, Ink · Inspirations Gallery · $36 / $42",
    description:
      "One-day workshop with Judy Reeves on creating atmosphere, mood, and emotion through description, setting, the senses, and diction. Explore techniques with in-workshop exercises you can apply to fiction and memoir/nonfiction. Wednesday, August 12, 2026, 6:30–8:30 PM PT at Inspirations Gallery. $36 members · $42 nonmembers.",
    category: "workshop",
    organizer: "San Diego Writers, Ink",
    venue: "Inspirations Gallery",
    address: "2730 Historic Decatur Rd #204, San Diego, CA 92106",
    neighborhood: "Liberty Station",
    rsvpUrl:
      "https://writeyourstorynow.org/classes-workshops/2026-08-12-creating-emotion-on-the-page-atmosphere-and-mood-with-judy-reeves/",
    price: "paid",
    priceDetail: "$36 members · $42 nonmembers",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdwi-once-upon-craft-camp-session1-20260817",
    year: 2026,
    monthIndex: 7,
    day: 17,
    hour: 10,
    minute: 0,
    endHour: 12,
    endMinute: 0,
    title: "Once Upon a Craft Camp (ages 5–8) — Session 1 with Ms. Whitney",
    tagline: "San Diego Writers, Ink · Aug 17–21 · 10 AM–12 PM · $150",
    description:
      "Weeklong story adventure for ages 5–8 with Whitney Wegman-Wood. Read a beloved children’s book each day, explore characters and themes, and bring stories to life through movement, theater games, and hands-on crafts. Session 1: Monday–Friday, August 17–21, 10:00 AM–12:00 PM at Inspirations Gallery. Max 12 participants. $150.",
    category: "workshop",
    organizer: "San Diego Writers, Ink",
    venue: "Inspirations Gallery",
    address: "2730 Historic Decatur Rd #204, San Diego, CA 92106",
    neighborhood: "Liberty Station",
    rsvpUrl: "https://secure.writeyourstorynow.org/eventReg.jsp?event=25579",
    price: "paid",
    priceDetail: "$150",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdwi-once-upon-craft-camp-session2-20260824",
    year: 2026,
    monthIndex: 7,
    day: 24,
    hour: 10,
    minute: 0,
    endHour: 12,
    endMinute: 0,
    title: "Once Upon a Craft Camp (ages 5–8) — Session 2 with Ms. Whitney",
    tagline: "San Diego Writers, Ink · Aug 24–28 · 10 AM–12 PM · $150",
    description:
      "Weeklong story adventure for ages 5–8 with Whitney Wegman-Wood. Read a beloved children’s book each day, explore characters and themes, and bring stories to life through movement, theater games, and hands-on crafts. Session 2: Monday–Friday, August 24–28, 10:00 AM–12:00 PM at Inspirations Gallery. Crafts do not repeat across weeks. Max 12 participants. $150.",
    category: "workshop",
    organizer: "San Diego Writers, Ink",
    venue: "Inspirations Gallery",
    address: "2730 Historic Decatur Rd #204, San Diego, CA 92106",
    neighborhood: "Liberty Station",
    rsvpUrl: "https://secure.writeyourstorynow.org/eventReg.jsp?event=25584",
    price: "paid",
    priceDetail: "$150",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdwi-sneaking-backdoor-poetry-prose-20260818",
    year: 2026,
    monthIndex: 7,
    day: 18,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 30,
    title: "Sneaking in the Backdoor of Poetry and Prose with Jill Badonsky",
    tagline: "San Diego Writers, Ink · Zoom · Session 2 of 3",
    description:
      "Second session of Jill Badonsky's three-week Zoom poetry and prose workshop (Tuesdays August 11, 18 & 25, 2:00–3:30 PM PT). Low-pressure prompts via lists, mind-mapping, and images. Zoom link emailed 24 hours before class. $81 members · $94.50 nonmembers.",
    category: "workshop",
    organizer: "San Diego Writers, Ink",
    venue: "Zoom (Live)",
    format: "virtual",
    virtualLabel: "Zoom (link emailed 24 hours before class)",
    rsvpUrl:
      "https://writeyourstorynow.org/classes-workshops/2026-08-11-sneaking-in-the-backdoor-of-poetry-and-prose-with-jill-badonsky/",
    price: "paid",
    priceDetail: "$81 members · $94.50 nonmembers",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdwi-sneaking-backdoor-poetry-prose-20260825",
    year: 2026,
    monthIndex: 7,
    day: 25,
    hour: 14,
    minute: 0,
    endHour: 15,
    endMinute: 30,
    title: "Sneaking in the Backdoor of Poetry and Prose with Jill Badonsky",
    tagline: "San Diego Writers, Ink · Zoom · Session 3 of 3",
    description:
      "Final session of Jill Badonsky's three-week Zoom poetry and prose workshop (Tuesdays August 11, 18 & 25, 2:00–3:30 PM PT). Low-pressure prompts via lists, mind-mapping, and images. Zoom link emailed 24 hours before class. $81 members · $94.50 nonmembers.",
    category: "workshop",
    organizer: "San Diego Writers, Ink",
    venue: "Zoom (Live)",
    format: "virtual",
    virtualLabel: "Zoom (link emailed 24 hours before class)",
    rsvpUrl:
      "https://writeyourstorynow.org/classes-workshops/2026-08-11-sneaking-in-the-backdoor-of-poetry-and-prose-with-jill-badonsky/",
    price: "paid",
    priceDetail: "$81 members · $94.50 nonmembers",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdpl-zoom-book-club-20260813",
    year: 2026,
    monthIndex: 7,
    day: 13,
    hour: 11,
    minute: 30,
    endHour: 12,
    endMinute: 30,
    title: "Zoom Book Club",
    tagline: "Virtual · Accessible book discussion",
    description:
      "Virtual literature book discussion for adults and older adults. Accessible program via San Diego Public Library.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Virtual Events",
    format: "virtual",
    virtualLabel: "Zoom (SDPL Virtual Events)",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-writers-open-mic-20260814",
    year: 2026,
    monthIndex: 7,
    day: 14,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    title: "Writer's Open Mic San Diego",
    tagline: "Expressive Arts @ 32nd & Thorn · 7–9 PM PT · $15 donation",
    description:
      "Every story needs to be heard! Monthly writers open mic (usually 2nd Fridays), 7:00–9:00 PM Pacific—arrive early so the evening can start on time. All levels welcome, beginners to professionals; bring something you've written to read (about 5 minutes) or come to listen. Poetry, prose, fiction, memoir, story, rant, scene—works from the heart and soul. $15 appreciated donation (pay what you can). Hosted by Tish Sjoberg at Expressive Arts @ 32nd & Thorn.",
    category: "open-mic",
    organizer: "Tish Sjoberg / Expressive Arts @ 32nd & Thorn",
    venue: "Expressive Arts @ 32nd & Thorn",
    address: "3201 Thorn Street, San Diego, CA 92104",
    neighborhood: "North Park",
    rsvpUrl:
      "https://www.eventbrite.com/e/writers-open-mic-san-diego-tickets-104558025870",
    price: "paid",
    priceDetail: "$15 appreciated donation (pay what you can)",
    registrationRequired: true,
    sourceChannel: "eventbrite",
    source: "Eventbrite — Writer's Open Mic San Diego",
  },
  {
    id: "sd-sdwi-jump-start-zoe-gharemani-20260808",
    year: 2026,
    monthIndex: 7,
    day: 8,
    hour: 10,
    minute: 0,
    endHour: 12,
    endMinute: 0,
    title: "The Jump Start You Need with Zoe Gharemani",
    tagline: "San Diego Writers, Ink · Session 1 of 2 · Inspirations Gallery",
    description:
      "Two-session workshop with Zoe Gharemani on the do's and don'ts of writing, attracting agents, and the road to publication. Participants are encouraged to share projects; the main goal is to motivate and generate new energy for the work ahead—and to have fun. Session 1: Saturday, August 8, 10:00 AM–12:00 PM. Session 2: Friday, August 14, 5:30–7:30 PM. $72 members · $84 nonmembers. Register at least a week before the start when possible.",
    category: "workshop",
    organizer: "San Diego Writers, Ink",
    venue: "Inspirations Gallery",
    address: "2730 Historic Decatur Rd #204, San Diego, CA 92106",
    neighborhood: "Liberty Station",
    rsvpUrl:
      "https://writeyourstorynow.org/classes-workshops/2026-08-08-the-jump-start-you-need-with-zoe-gharemani/",
    price: "paid",
    priceDetail: "$72 members · $84 nonmembers",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdwi-jump-start-zoe-gharemani-20260814",
    year: 2026,
    monthIndex: 7,
    day: 14,
    hour: 17,
    minute: 30,
    endHour: 19,
    endMinute: 30,
    title: "The Jump Start You Need with Zoe Gharemani",
    tagline: "San Diego Writers, Ink · Session 2 of 2 · Inspirations Gallery",
    description:
      "Second session of Zoe Gharemani's two-part workshop on writing craft, agents, and publication (with Session 1 on Saturday, August 8, 10:00 AM–12:00 PM). Participants are encouraged to share projects; the main goal is to motivate and generate new energy for the work ahead—and to have fun. $72 members · $84 nonmembers.",
    category: "workshop",
    organizer: "San Diego Writers, Ink",
    venue: "Inspirations Gallery",
    address: "2730 Historic Decatur Rd #204, San Diego, CA 92106",
    neighborhood: "Liberty Station",
    rsvpUrl:
      "https://writeyourstorynow.org/classes-workshops/2026-08-08-the-jump-start-you-need-with-zoe-gharemani/",
    price: "paid",
    priceDetail: "$72 members · $84 nonmembers",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-dog-friendly-open-mic-20260821",
    year: 2026,
    monthIndex: 7,
    day: 21,
    hour: 18,
    minute: 0,
    endHour: 20,
    endMinute: 30,
    title: "Dog Friendly Open Mic Night",
    tagline: "Pure Pawsh · Free · Bring your pup",
    description:
      "Grab a drink, bring your pup, and share your art—songs, poems, comedy, stories, or special talents. Sign-ups begin at 6:00 PM; show starts at 6:30 PM. Hosted by Shanny Mac. All ages welcome; dog friendly. Free.",
    category: "open-mic",
    organizer: "Pure Pawsh",
    venue: "Pure Pawsh",
    address: "4045 30th Street, San Diego, CA 92104",
    neighborhood: "North Park",
    rsvpUrl:
      "https://www.eventbrite.com/e/dog-friendly-open-mic-night-tickets-1996184846612",
    price: "free",
    registrationRequired: true,
    sourceChannel: "eventbrite",
    source: "Eventbrite — Pure Pawsh",
  },
  {
    id: "sd-mental-bar-open-mic-20260822",
    year: 2026,
    monthIndex: 7,
    day: 22,
    hour: 18,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    title: "Open Mic Night at the Mental Bar",
    tagline: "The Mental Bar · Free admission · Poets & storytellers welcome",
    description:
      "Saturday, August 22, 6:00–9:00 PM PT—an evening of creativity, connection, and good vibes. Musicians, poets, storytellers, comedians, and creatives of all kinds are welcome to take the mic. Hosted by Brandon Flowers & The gARTen Network. Open Mic · Karaoke · Painting · DJ DM. Admission is free; optional canvas painting ($25) and vinyl painting ($30) available.",
    category: "open-mic",
    organizer: "The Mental Bar",
    venue: "The Mental Bar — Coffee, Tea & Wellness",
    address: "6325 Imperial Avenue #Suite 103, San Diego, CA 92114",
    neighborhood: "San Diego",
    rsvpUrl:
      "https://www.eventbrite.com/e/open-mic-night-at-the-mental-bar-tickets-1993840745342",
    price: "free",
    priceDetail: "Free admission · optional painting $25–$30",
    registrationRequired: true,
    sourceChannel: "eventbrite",
    source: "Eventbrite — The Mental Bar",
  },
  {
    id: "sd-sdpl-banned-book-club-20260825",
    year: 2026,
    monthIndex: 7,
    day: 25,
    hour: 18,
    minute: 30,
    endHour: 19,
    endMinute: 30,
    title: "Banned Book Club (Virtual)",
    tagline: "Mira Mesa Library · Virtual literature discussion",
    description:
      "Virtual banned book club discussion focused on literature, hosted through Mira Mesa Library for adults, emerging adults, and older adults.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Mira Mesa Library (virtual)",
    neighborhood: "Mira Mesa",
    format: "virtual",
    virtualLabel: "Virtual via Mira Mesa Library",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdpl-author-talk-ashley-hanna-morgan-20260825",
    year: 2026,
    monthIndex: 7,
    day: 25,
    hour: 18,
    minute: 30,
    endHour: 20,
    endMinute: 0,
    title: "Author Talk: Ashley Hanna-Morgan",
    tagline: "Pacific Beach/Taylor Library · Local author",
    description:
      "Author talk with Ashley Hanna-Morgan at Pacific Beach/Taylor Library. Literature and local author focus; open to adults, emerging adults, older adults, and teens.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Pacific Beach/Taylor Library",
    neighborhood: "Pacific Beach",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdpl-mystery-book-club-20260826",
    year: 2026,
    monthIndex: 7,
    day: 26,
    hour: 15,
    minute: 0,
    endHour: 16,
    endMinute: 30,
    title: "Mystery Book Club",
    tagline: "Mission Hills-Hillcrest/Knox Library · Book discussion",
    description:
      "Adult mystery book discussion focused on literature at Mission Hills-Hillcrest/Knox Library.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Mission Hills-Hillcrest/Knox Library",
    neighborhood: "Mission Hills / Hillcrest",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-write-about-now-poetry-20260828",
    year: 2026,
    monthIndex: 7,
    day: 28,
    hour: 19,
    minute: 30,
    endHour: 22,
    endMinute: 30,
    title:
      "Write About Now Poetry Live in San Diego ft. Grammy-nominated Shawn William",
    tagline: "Handlery Hotel · 7:30–10:30 PM PT · Featured poet Shawn William",
    description:
      "Write About Now Poetry Live in San Diego, hosted by Mason Granger, featuring Grammy-nominated spoken word artist Shawn William (Oakland). Open mic signup lists go up at 7:30 PM; doors open 7:30 PM, show starts by 8:00 PM or earlier. Open to all. Full bar available; $3 event parking at the venue. Ticket price via Eventbrite.",
    category: "open-mic",
    organizer: "Write About Now Poetry",
    venue: "Handlery Hotel San Diego",
    address: "950 Hotel Circle North, San Diego, CA 92108",
    neighborhood: "Hotel Circle",
    rsvpUrl:
      "https://www.eventbrite.com/e/write-about-now-poetry-live-in-san-diego-ft-grammy-nominated-shawn-william-tickets-1992066974947",
    price: "unknown",
    priceDetail: "See Eventbrite · $3 event parking",
    registrationRequired: true,
    sourceChannel: "eventbrite",
    source: "Eventbrite — Write About Now Poetry",
  },

  // —— September 2026 ——
  {
    id: "sd-sdwi-wednesday-evening-book-club-20260902",
    year: 2026,
    monthIndex: 8,
    day: 2,
    hour: 18,
    minute: 0,
    endHour: 19,
    endMinute: 0,
    title: "Wednesday Evening Book Club with Rebecca Li",
    tagline: "San Diego Writers, Ink · Zoom · Laufey's Book Club · $15",
    description:
      "Laufey's Book Club with Rebecca Li—discuss one of Laufey's picks (typically fiction with a whimsical bent), identify craft elements you love, and talk about using them in your own writing. Meets once every two months on Zoom. Wednesday, September 2, 6:00–7:00 PM PT. $15 for members and nonmembers. Zoom link emailed 24 hours before class.",
    category: "reading",
    organizer: "San Diego Writers, Ink",
    venue: "Zoom (Live)",
    format: "virtual",
    virtualLabel: "Zoom (link emailed 24 hours before class)",
    rsvpUrl: "https://secure.writeyourstorynow.org/eventReg.jsp?event=25556",
    price: "paid",
    priceDetail: "$15",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Writers, Ink (writeyourstorynow.org)",
  },
  {
    id: "sd-sdpl-gay-mens-book-club-20260901",
    year: 2026,
    monthIndex: 8,
    day: 1,
    hour: 18,
    minute: 0,
    endHour: 19,
    endMinute: 30,
    title: "Gay Men's Book Club",
    tagline: "Mission Hills-Hillcrest/Knox Library · Literature & LGBTQ+",
    description:
      "Adult book discussion focused on literature and LGBTQ+ themes at Mission Hills-Hillcrest/Knox Library.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Mission Hills-Hillcrest/Knox Library",
    neighborhood: "Mission Hills / Hillcrest",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdpl-off-beat-book-club-20260901",
    year: 2026,
    monthIndex: 8,
    day: 1,
    hour: 18,
    minute: 30,
    endHour: 20,
    endMinute: 0,
    title: "Off-Beat Book Club",
    tagline: "Ocean Beach Library · Book discussion",
    description:
      "Adult book discussion focused on literature at Ocean Beach Library.",
    category: "reading",
    organizer: "San Diego Public Library",
    venue: "Ocean Beach Library",
    neighborhood: "Ocean Beach",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdpl-ai-storymasters-20260904",
    year: 2026,
    monthIndex: 8,
    day: 4,
    hour: 11,
    minute: 30,
    endHour: 13,
    endMinute: 0,
    title: "AI Storymasters: Creative Writing for Adults & Seniors",
    tagline: "North University Community Library · Creative writing",
    description:
      "Creative writing workshop for adults, emerging adults, and older adults at North University Community Library, with a literature focus.",
    category: "workshop",
    organizer: "San Diego Public Library",
    venue: "North University Community Library",
    neighborhood: "University City",
    rsvpUrl: SDPL_CAL,
    rsvpIsGeneralCalendar: true,
    price: "free",
    sourceChannel: "library",
  },
  {
    id: "sd-sdmwa-querying-for-memoir-20260912",
    year: 2026,
    monthIndex: 8,
    day: 12,
    hour: 14,
    minute: 30,
    endHour: 16,
    endMinute: 0,
    title: "Querying for Memoir",
    tagline: "SDMWA · Zoom · Lyn Liao Butler · 2:30 PM PT",
    description:
      "You've written your memoir—now comes the query letter. Join bestselling author Lyn Liao Butler for an inside look at what agents are looking for and how to craft a query that showcases the heart of your story. Learn essential elements of a compelling query, common mistakes, and practical strategies to help your memoir stand out. Hosted by the San Diego Memoir Writers Association on Zoom. Saturday, September 12, 2026, 2:30 PM PT. Free for SDMWA members.",
    category: "workshop",
    organizer: "San Diego Memoir Writers Association",
    venue: "Zoom",
    format: "virtual",
    virtualLabel: "Zoom",
    rsvpUrl: "https://sdmwa.org/event/querying-for-memoir/",
    price: "free",
    priceDetail: "Free for SDMWA members",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Memoir Writers Association (sdmwa.org)",
  },
  {
    id: "sd-sdmwa-is-my-memoir-a-film-20261003",
    year: 2026,
    monthIndex: 9,
    day: 3,
    hour: 14,
    minute: 30,
    endHour: 16,
    endMinute: 0,
    title: "Is My Memoir a Film?",
    tagline: "SDMWA · Zoom · Carlos de los Ríos · 2:30 PM PT",
    description:
      "What transforms a memoir into a movie? Filmmaker Carlos de los Ríos explores the qualities that make certain life stories irresistible to filmmakers—what creates cinematic momentum and how to see your story through a film lens. Hosted by the San Diego Memoir Writers Association on Zoom. Saturday, October 3, 2026, 2:30 PM PT. Free for SDMWA members.",
    category: "workshop",
    organizer: "San Diego Memoir Writers Association",
    venue: "Zoom",
    format: "virtual",
    virtualLabel: "Zoom",
    rsvpUrl: "https://sdmwa.org/event/is-my-memoir-a-film/",
    price: "free",
    priceDetail: "Free for SDMWA members",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Memoir Writers Association (sdmwa.org)",
  },
  {
    id: "sd-sdmwa-artistic-badassery-20261107",
    year: 2026,
    monthIndex: 10,
    day: 7,
    hour: 14,
    minute: 30,
    endHour: 16,
    endMinute: 0,
    title: "Artistic Badassery for Writers – SDWF/IMWA Event",
    tagline: "SDMWA / SDWF · Zoom · Marni Freedman · 2:30 PM PT",
    description:
      "Every memoir begins with one brave act: showing up to the page. Author and creativity teacher Marni Freedman shares tools from her book Artistic Badassery: How to Unblock and Become a Creative Force of Nature—quiet your inner critic, reconnect with your authentic voice, and create with greater courage, joy, and flow. Presented with the San Diego Writers Festival and International Memoir Writers Association on Zoom. Saturday, November 7, 2026, 2:30 PM PT. Free for SDMWA members.",
    category: "workshop",
    organizer: "San Diego Memoir Writers Association",
    venue: "Zoom",
    format: "virtual",
    virtualLabel: "Zoom",
    rsvpUrl: "https://sdmwa.org/event/tools-to-unlock-your-fearless-self/",
    price: "free",
    priceDetail: "Free for SDMWA members",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Memoir Writers Association (sdmwa.org)",
  },
  {
    id: "sd-sdmwa-prompt-party-open-mic-20261205",
    year: 2026,
    monthIndex: 11,
    day: 5,
    hour: 14,
    minute: 30,
    endHour: 16,
    endMinute: 0,
    title: "IMWA Prompt Party Open Mic",
    tagline: "SDMWA / IMWA · Zoom · 2:30 PM PT",
    description:
      "One last writing adventure before the year ends! Join the IMWA community for an afternoon of inspiring prompts, spontaneous storytelling, and open mic-style sharing. Write, laugh, surprise yourself, and maybe discover the beginning of your next memoir—whether you share or simply listen. Hosted by the San Diego Memoir Writers Association / International Memoir Writers Association on Zoom. Saturday, December 5, 2026, 2:30 PM PT. Free for SDMWA members.",
    category: "open-mic",
    organizer: "San Diego Memoir Writers Association",
    venue: "Zoom",
    format: "virtual",
    virtualLabel: "Zoom",
    rsvpUrl: "https://sdmwa.org/event/prompt-party/",
    price: "free",
    priceDetail: "Free for SDMWA members",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Memoir Writers Association (sdmwa.org)",
  },
  {
    id: "sd-sdmwa-memoir-showcase-20261120",
    year: 2026,
    monthIndex: 10,
    day: 20,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    title: "12th Annual Theatrical Memoir Showcase",
    tagline: "SDMWA · Live performance · Theme: Home · Fri Nov 20 · 7 PM PT",
    description:
      "The Memoir Showcase is SDMWA's annual contest for five-page true stories (theme: Home), with two paths to publication: 8–9 winning stories are professionally edited and performed live by actors at the Theatrical Memoir Showcase, and an additional 20 appear in Shaking the Tree: brazen. short. memoir., Volume 10 (early 2029). Showcase winners also appear in the anthology. Live performance: Friday, November 20, 2026, 7:00 PM PT (typically at the David and Dorothea Garfield Theater, University City). Submission fees from $55 (IMWA member, one story). Pay first, then submit via the contest page.",
    category: "reading",
    organizer: "San Diego Memoir Writers Association",
    venue: "David and Dorothea Garfield Theater",
    address: "University City, San Diego, CA",
    neighborhood: "University City",
    rsvpUrl: "https://sdmwa.org/showcase-2025/",
    price: "unknown",
    priceDetail: "Contest entry from $55 · performance ticket price TBA",
    registrationRequired: true,
    sourceChannel: "literary_org",
    source: "San Diego Memoir Writers Association (sdmwa.org)",
  },
];

function mapSpec(spec: CuratedSpec): WorkshopEvent {
  const start = DateTime.fromObject(
    {
      year: spec.year,
      month: spec.monthIndex + 1,
      day: spec.day,
      hour: spec.hour,
      minute: spec.minute ?? 0,
      second: 0,
      millisecond: 0,
    },
    { zone: TZ },
  );
  const end =
    spec.endHour != null
      ? DateTime.fromObject(
          {
            year: spec.year,
            month: spec.monthIndex + 1,
            day: spec.day,
            hour: spec.endHour,
            minute: spec.endMinute ?? 0,
            second: 0,
            millisecond: 0,
          },
          { zone: TZ },
        )
      : start.plus({ hours: 1, minutes: 30 });

  return {
    id: spec.id,
    cityId: "sd",
    title: spec.title,
    tagline: spec.tagline,
    description: spec.description,
    start: start.toISO() ?? start.toString(),
    end: end.toISO() ?? undefined,
    timeZone: TZ,
    format: spec.format ?? "in-person",
    price: spec.price ?? "unknown",
    priceDetail: spec.priceDetail,
    registrationRequired: spec.registrationRequired,
    category: spec.category,
    organizer: spec.organizer,
    venue: spec.venue,
    address: spec.address,
    neighborhood: spec.neighborhood,
    virtualLabel: spec.virtualLabel,
    rsvpUrl: spec.rsvpUrl,
    rsvpIsGeneralCalendar: spec.rsvpIsGeneralCalendar,
    source: spec.source ?? "San Diego curated listings",
    sourceChannel: spec.sourceChannel ?? "literary_org",
    listingProvenance: "live",
  };
}

export type SanDiegoCuratedMeta = {
  curatedTotal: number;
  rowsInMonth: number;
};

export function fetchSanDiegoCuratedEventsForMonth(
  year: number,
  monthIndex: number,
): { events: WorkshopEvent[]; meta: SanDiegoCuratedMeta } {
  const rows = EVENTS.filter(
    (e) => e.year === year && e.monthIndex === monthIndex,
  ).map(mapSpec);
  rows.sort(
    (a, b) => new Date(a.start).getTime() - new Date(b.start).getTime(),
  );
  return {
    events: rows,
    meta: { curatedTotal: EVENTS.length, rowsInMonth: rows.length },
  };
}
