import { DateTime } from "luxon";
import type {
  WorkshopEvent,
  WorkshopEventCategory,
} from "@/lib/workshop-types";

const TZ = "America/Los_Angeles";

type CuratedSpec = {
  id: string;
  year: number;
  monthIndex: number;
  day: number;
  hour: number;
  minute: number;
  endHour?: number;
  endMinute?: number;
  timeZone: string;
  title: string;
  tagline: string;
  description: string;
  category: WorkshopEventCategory;
  organizer: string;
  venue: string;
  address: string;
  neighborhood: string;
  rsvpUrl: string;
  sourceChannel: WorkshopEvent["sourceChannel"];
  price?: WorkshopEvent["price"];
};

const CURATED: CuratedSpec[] = [
  {
    id: "sf-gab-9th-ave-jonathan-weber-quentin-hardy-20260701",
    year: 2026,
    monthIndex: 6,
    day: 1,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Jonathan Weber with Quentin Hardy",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Jonathan Weber with Quentin Hardy. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-01/9th-ave-jonathan-weber-quentin-hardy",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-offsite-gary-paul-nabhan-sf-botanical-ga-20260702",
    year: 2026,
    monthIndex: 6,
    day: 2,
    hour: 17,
    minute: 30,
    timeZone: TZ,
    title: "Gary Paul Nabhan at SF Botanical Garden",
    tagline: "Green Apple Books · Golden Gate Park · RSVP",
    description: "Green Apple Books presents Gary Paul Nabhan at SF Botanical Garden. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "SF Botanical Garden",
    address: "San Francisco, CA",
    neighborhood: "Golden Gate Park",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-02/offsite-gary-paul-nabhan-sf-botanical-garden",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-maria-lenhart-20260707",
    year: 2026,
    monthIndex: 6,
    day: 7,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Maria Lenhart",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Maria Lenhart. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-07/9th-ave-maria-lenhart",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-katie-gaddini-moira-donegan-20260709",
    year: 2026,
    monthIndex: 6,
    day: 9,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Katie Gaddini with Moira Donegan",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Katie Gaddini with Moira Donegan. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-09/9th-ave-katie-gaddini-moira-donegan",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-jake-skeets-beth-piatote-20260715",
    year: 2026,
    monthIndex: 6,
    day: 15,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Jake Skeets with Beth Piatote",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Jake Skeets with Beth Piatote. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-15/9th-ave-jake-skeets-beth-piatote",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-gary-phillips-20260717",
    year: 2026,
    monthIndex: 6,
    day: 17,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Gary Phillips",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Gary Phillips. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-17/9th-ave-gary-phillips",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-claire-vaye-watkins-daniel-gumbi-20260722",
    year: 2026,
    monthIndex: 6,
    day: 22,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Claire Vaye Watkins with Daniel Gumbiner",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Claire Vaye Watkins with Daniel Gumbiner. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-22/9th-ave-claire-vaye-watkins-daniel-gumbiner",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-nick-greene-benjamin-gucciardi-20260723",
    year: 2026,
    monthIndex: 6,
    day: 23,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Nick Greene with Benjamin Gucciardi",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Nick Greene with Benjamin Gucciardi. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-23/9th-ave-nick-greene-benjamin-gucciardi",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-clement-st-dave-eggers-book-signing-20260725",
    year: 2026,
    monthIndex: 6,
    day: 25,
    hour: 19,
    minute: 30,
    endHour: 20,
    endMinute: 30,
    timeZone: TZ,
    title: "Dave Eggers Book Signing",
    tagline: "Green Apple Books · Inner Richmond · Free · RSVP",
    description: "Green Apple Books presents Dave Eggers Book Signing. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on Clement",
    address: "506 Clement St, San Francisco, CA 94118",
    neighborhood: "Inner Richmond",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-25/clement-st-dave-eggers-book-signing",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-emeline-atwood-rebecca-handler-20260728",
    year: 2026,
    monthIndex: 6,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Emeline Atwood with Rebecca Handler",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Emeline Atwood with Rebecca Handler. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-07-28/9th-ave-emeline-atwood-rebecca-handler",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-larry-hayes-20260804",
    year: 2026,
    monthIndex: 7,
    day: 4,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Larry Hayes",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Larry Hayes. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-08-04/9th-ave-larry-hayes",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-afsheen-farhadi-corey-sobel-20260805",
    year: 2026,
    monthIndex: 7,
    day: 5,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Afsheen Farhadi with Corey Sobel",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Afsheen Farhadi with Corey Sobel. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-08-05/9th-ave-afsheen-farhadi-corey-sobel",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-jill-bronfman-20260812",
    year: 2026,
    monthIndex: 7,
    day: 12,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Jill Bronfman",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Jill Bronfman. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-08-12/9th-ave-jill-bronfman",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-lenna-jawdat-20260819",
    year: 2026,
    monthIndex: 7,
    day: 19,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Lenna Jawdat",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Lenna Jawdat. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-08-19/9th-ave-lenna-jawdat",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-chang-rae-lee-ro-kwon-20260820",
    year: 2026,
    monthIndex: 7,
    day: 20,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Chang-rae Lee with R.O. Kwon",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Chang-rae Lee with R.O. Kwon. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-08-20/9th-ave-chang-rae-lee-ro-kwon",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-valerie-hsiung-jennifer-s-cheng--20260827",
    year: 2026,
    monthIndex: 7,
    day: 27,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Valerie Hsiung, Jennifer S. Cheng, Jennifer Elise Foerster, and Samantha Giles",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Valerie Hsiung, Jennifer S. Cheng, Jennifer Elise Foerster, and Samantha Giles. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-08-27/9th-ave-valerie-hsiung-jennifer-s-cheng-jennifer-elise-foerster-and-samantha-giles",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-dvan-presents-carolyn-huynh-trin-20260828",
    year: 2026,
    monthIndex: 7,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "DVAN presents Carolyn Huynh, Trinity Nguyen, and Aimee Phan",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Carolyn Huynh, Trinity Nguyen, and Aimee Phan (DVAN). See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-08-28/9th-ave-dvan-presents-carolyn-huynh-trinity-nguyen-and-aimee-phan",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-black-ocean-20th-anniversary-cel-20260903",
    year: 2026,
    monthIndex: 8,
    day: 3,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Black Ocean 20th Anniversary Celebration",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Black Ocean 20th Anniversary Celebration. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-09-03/9th-ave-black-ocean-20th-anniversary-celebration",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-anna-nordberg-rachel-levin-20260909",
    year: 2026,
    monthIndex: 8,
    day: 9,
    hour: 19,
    minute: 0,
    endHour: 19,
    endMinute: 15,
    timeZone: TZ,
    title: "Anna Nordberg with Rachel Levin",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Anna Nordberg with Rachel Levin. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-09-09/9th-ave-anna-nordberg-rachel-levin",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-melissa-dalton-bradford-20260910",
    year: 2026,
    monthIndex: 8,
    day: 10,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Melissa Dalton-Bradford",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Melissa Dalton-Bradford. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-09-10/9th-ave-melissa-dalton-bradford",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-nina-schuyler-20260914",
    year: 2026,
    monthIndex: 8,
    day: 14,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Nina Schuyler",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Nina Schuyler. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-09-14/9th-ave-nina-schuyler",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-leah-c-stokes-rebecca-solnit-20260916",
    year: 2026,
    monthIndex: 8,
    day: 16,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Leah C. Stokes with Rebecca Solnit",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Leah C. Stokes with Rebecca Solnit. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-09-16/9th-ave-leah-c-stokes-rebecca-solnit",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-splendor-trans-poets-translation-20260917",
    year: 2026,
    monthIndex: 8,
    day: 17,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Splendor: Trans Poets in Translation",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Splendor: Trans Poets in Translation. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-09-17/9th-ave-splendor-trans-poets-translation",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-diana-kapp-20260928",
    year: 2026,
    monthIndex: 8,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Diana Kapp",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Diana Kapp. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-09-28/9th-ave-diana-kapp",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-wordnight-usf-20260930",
    year: 2026,
    monthIndex: 8,
    day: 30,
    hour: 18,
    minute: 30,
    timeZone: TZ,
    title: "Wordnight with USF",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Wordnight with USF. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-09-30/9th-ave-wordnight-usf",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-tomas-moniz-20261001",
    year: 2026,
    monthIndex: 9,
    day: 1,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Tomas Moniz",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Tomas Moniz. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-01/9th-ave-tomas-moniz",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-gab-9th-ave-ts-leonard-20261005",
    year: 2026,
    monthIndex: 9,
    day: 5,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "T.S. Leonard",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents T.S. Leonard. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-05/9th-ave-ts-leonard",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-annalee-newitz-20261006",
    year: 2026,
    monthIndex: 9,
    day: 6,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Annalee Newitz",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Annalee Newitz. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-06/9th-ave-annalee-newitz",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-offsite-jon-ronson-20261014",
    year: 2026,
    monthIndex: 9,
    day: 14,
    hour: 19,
    minute: 0,
    endHour: 19,
    endMinute: 15,
    timeZone: TZ,
    title: "Jon Ronson",
    tagline: "Green Apple Books · San Francisco · RSVP",
    description: "Green Apple Books presents Jon Ronson. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Offsite",
    address: "San Francisco, CA",
    neighborhood: "San Francisco",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-14/offsite-jon-ronson",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-benjamin-gucciardi-20261015",
    year: 2026,
    monthIndex: 9,
    day: 15,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Benjamin Gucciardi",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Benjamin Gucciardi. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-15/9th-ave-benjamin-gucciardi",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-kawai-strong-washburn-20261019",
    year: 2026,
    monthIndex: 9,
    day: 19,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Kawai Strong Washburn",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Kawai Strong Washburn. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-19/9th-ave-kawai-strong-washburn",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-nicholas-russell-ginger-greene-20261022",
    year: 2026,
    monthIndex: 9,
    day: 22,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Nicholas Russell with Ginger Greene",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Nicholas Russell with Ginger Greene. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-22/9th-ave-nicholas-russell-ginger-greene",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-k-ming-chang-20261023",
    year: 2026,
    monthIndex: 9,
    day: 23,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "K-Ming Chang",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents K-Ming Chang. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-23/9th-ave-k-ming-chang",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-fady-joudah-20261026",
    year: 2026,
    monthIndex: 9,
    day: 26,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Fady Joudah",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Fady Joudah. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-26/9th-ave-fady-joudah",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-andrew-miller-20261027",
    year: 2026,
    monthIndex: 9,
    day: 27,
    hour: 19,
    minute: 0,
    endHour: 19,
    endMinute: 15,
    timeZone: TZ,
    title: "Andrew Miller",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Andrew Miller. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-27/9th-ave-andrew-miller",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-daisy-fried-20261028",
    year: 2026,
    monthIndex: 9,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Daisy Fried",
    tagline: "Green Apple Books · Inner Sunset · RSVP",
    description: "Green Apple Books presents Daisy Fried. See listing for details.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-28/9th-ave-daisy-fried",
    sourceChannel: "bookstore",
  },
  {
    id: "sf-gab-9th-ave-kirk-lombard-20261030",
    year: 2026,
    monthIndex: 9,
    day: 30,
    hour: 18,
    minute: 0,
    timeZone: TZ,
    title: "Kirk Lombard",
    tagline: "Green Apple Books · Inner Sunset · Free · RSVP",
    description: "Green Apple Books presents Kirk Lombard. Free; please RSVP.",
    category: "reading",
    organizer: "Green Apple Books",
    venue: "Green Apple Books on the Park (9th Ave)",
    address: "1231 9th Ave, San Francisco, CA 94122",
    neighborhood: "Inner Sunset",
    rsvpUrl: "https://greenapplebooks.com/event/2026-10-30/9th-ave-kirk-lombard",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-litquake-pub-trivia-20260727",
    year: 2026,
    monthIndex: 6,
    day: 27,
    hour: 18,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "Litquake's Literary Pub Trivia: 2026 Double Feature",
    tagline: "Litquake · Berkeley · RSVP",
    description: "Our popular pub trivia is coming to you twice in 2026. Literary pub trivia at 912 Gilman St, Berkeley.",
    category: "reading",
    organizer: "Litquake",
    venue: "912 Gilman St",
    address: "912 Gilman St, Berkeley, CA 94710",
    neighborhood: "Berkeley",
    rsvpUrl: "https://www.litquake.org/upcoming-events",
    sourceChannel: "literary_org",
  },
  {
    id: "sf-litquake-write-together-20260801",
    year: 2026,
    monthIndex: 7,
    day: 1,
    hour: 10,
    minute: 30,
    endHour: 12,
    endMinute: 30,
    timeZone: TZ,
    title: "Write Together August",
    tagline: "Litquake · LitCamp · San Francisco · RSVP",
    description: "Join Litquake and LitCamp for 90 minutes of writing in community.",
    category: "workshop",
    organizer: "Litquake",
    venue: "297 Page St",
    address: "297 Page St, San Francisco, CA 94102",
    neighborhood: "Hayes Valley",
    rsvpUrl: "https://www.litquake.org/upcoming-events",
    sourceChannel: "literary_org",
  },
  {
    id: "sf-litquake-susan-stryker-20260910",
    year: 2026,
    monthIndex: 8,
    day: 10,
    hour: 19,
    minute: 0,
    endHour: 20,
    endMinute: 30,
    timeZone: TZ,
    title: "Changing Gender: Susan Stryker",
    tagline: "Litquake · Oakland · RSVP",
    description: "Leading trans scholar Susan Stryker discusses her latest book at Oakstop California Ballroom.",
    category: "reading",
    organizer: "Litquake",
    venue: "Oakstop - California Ballroom",
    address: "1736 Franklin St, Oakland, CA 94612",
    neighborhood: "Oakland",
    rsvpUrl: "https://www.litquake.org/upcoming-events",
    sourceChannel: "literary_org",
  },
  {
    id: "sf-litquake-zyzzyva-solnit-20260917",
    year: 2026,
    monthIndex: 8,
    day: 17,
    hour: 18,
    minute: 0,
    endHour: 20,
    endMinute: 0,
    timeZone: TZ,
    title: "ZYZZYVA Movie Night with Ingrid Rojas Contreras and Rebecca Solnit",
    tagline: "Litquake · Roxie Theater · SF",
    description: "Ingrid Rojas Contreras presents a special screening of Songs of Earth, selected by Rebecca Solnit.",
    category: "reading",
    organizer: "Litquake",
    venue: "Roxie Theater",
    address: "3117 16th St, San Francisco, CA 94103",
    neighborhood: "Mission",
    rsvpUrl: "https://www.litquake.org/upcoming-events",
    sourceChannel: "literary_org",
  },
  {
    id: "sf-litquake-rf-kuang-20260923",
    year: 2026,
    monthIndex: 8,
    day: 23,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 30,
    timeZone: TZ,
    title: "R.F. Kuang: Taipei Story with Abigail Hing Wen",
    tagline: "Litquake · Calvary Presbyterian · SF",
    description: "An evening with award-winning author R.F. Kuang in conversation with Abigail Hing Wen.",
    category: "reading",
    organizer: "Litquake",
    venue: "Calvary Presbyterian Church",
    address: "2515 Fillmore St, San Francisco, CA 94115",
    neighborhood: "Pacific Heights",
    rsvpUrl: "https://www.litquake.org/upcoming-events",
    sourceChannel: "literary_org",
  },
  {
    id: "sf-litquake-out-loud-20261004",
    year: 2026,
    monthIndex: 9,
    day: 4,
    hour: 11,
    minute: 0,
    endHour: 16,
    endMinute: 0,
    timeZone: TZ,
    title: "Litquake Out Loud",
    tagline: "Litquake · Yerba Buena Gardens · SF",
    description: "Bay Area BIPOC & LGBTQ+ writers curate a daytime series of outdoor events at Yerba Buena Gardens.",
    category: "reading",
    organizer: "Litquake",
    venue: "Yerba Buena Gardens",
    address: "750 Howard St, San Francisco, CA 94103",
    neighborhood: "SoMa",
    rsvpUrl: "https://www.litquake.org/upcoming-events",
    sourceChannel: "literary_org",
  },
  {
    id: "sf-litquake-ayad-akhtar-20261006",
    year: 2026,
    monthIndex: 9,
    day: 6,
    hour: 19,
    minute: 30,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "The Radiance: Ayad Akhtar with Karen Russell",
    tagline: "Litquake · City Arts & Lectures · Sydney Goldstein Theater",
    description: "Ayad Akhtar in conversation with Karen Russell at Sydney Goldstein Theater.",
    category: "reading",
    organizer: "Litquake",
    venue: "Sydney Goldstein Theater",
    address: "275 Hayes St, San Francisco, CA 94102",
    neighborhood: "Hayes Valley",
    rsvpUrl: "https://www.litquake.org/upcoming-events",
    sourceChannel: "literary_org",
    price: "paid",
  },
  {
    id: "sf-litquake-zyzzyva-greer-20261017",
    year: 2026,
    monthIndex: 9,
    day: 17,
    hour: 12,
    minute: 30,
    endHour: 14,
    endMinute: 30,
    timeZone: TZ,
    title: "ZYZZYVA Movie Matinee with Ingrid Rojas Contreras and Andrew Sean Greer",
    tagline: "Litquake · Roxie Theater · SF",
    description: "Ingrid Rojas Contreras presents a special screening of Amarcord, selected by Andrew Sean Greer.",
    category: "reading",
    organizer: "Litquake",
    venue: "Roxie Theater",
    address: "3117 16th St, San Francisco, CA 94103",
    neighborhood: "Mission",
    rsvpUrl: "https://www.litquake.org/upcoming-events",
    sourceChannel: "literary_org",
  },
  {
    id: "sf-citylights-greg-sarris-in-conversation-with-oscar-v-20260723",
    year: 2026,
    monthIndex: 6,
    day: 23,
    hour: 18,
    minute: 30,
    timeZone: TZ,
    title: "Greg Sarris in conversation with Oscar Villalon — The Last Human Bear",
    tagline: "City Lights · North Beach · Free",
    description: "City Lights and Heyday Books celebrate The Last Human Bear in Kerouac Alley.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-trevor-paglen-how-to-see-like-a-machine-20260725",
    year: 2026,
    monthIndex: 6,
    day: 25,
    hour: 11,
    minute: 0,
    timeZone: TZ,
    title: "Trevor Paglen — How To See Like A Machine: Images After AI",
    tagline: "City Lights · North Beach · Free",
    description: "City Lights and Verso Books celebrate How To See Like A Machine by Trevor Paglen.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-maxine-chernoff-friends-diary-poems-20260726",
    year: 2026,
    monthIndex: 6,
    day: 26,
    hour: 12,
    minute: 0,
    timeZone: TZ,
    title: "Maxine Chernoff & Friends — DIARY:POEMS",
    tagline: "City Lights · North Beach · Free",
    description: "Maxine Chernoff with Paul Hoover, Claudia Keelan, Roxi Power Hamilton, and Cole Swenson for DIARY:POEMS.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-jeanne-carstensen-in-conversation-with-s-20260727",
    year: 2026,
    monthIndex: 6,
    day: 27,
    hour: 18,
    minute: 0,
    timeZone: TZ,
    title: "Jeanne Carstensen in conversation with Saumya Roy — A Greek Tragedy",
    tagline: "City Lights · North Beach · Free",
    description: "City Lights celebrates the paperback of A Greek Tragedy by Jeanne Carstensen.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-wesleyan-university-press-showcase-20260728",
    year: 2026,
    monthIndex: 6,
    day: 28,
    hour: 18,
    minute: 0,
    timeZone: TZ,
    title: "Wesleyan University Press Showcase",
    tagline: "City Lights · North Beach · Free",
    description: "City Lights and Wesleyan University Press celebrate new seasonal work with Carol Ann Davis, Edgar Garcia, Cindy Juyoung Ok, and Sandra Simonds.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-rayelle-davis-money-in-the-mountains-20260803",
    year: 2026,
    monthIndex: 7,
    day: 3,
    hour: 18,
    minute: 0,
    timeZone: TZ,
    title: "Rayelle Davis — Money in the Mountains",
    tagline: "City Lights · North Beach · Free",
    description: "Rayelle Davis in conversation with Jolene McIlwain on Money in the Mountains: The Cultural Trauma of Appalachia.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-the-dial-city-lights-mara-wilson-with-sa-20260811",
    year: 2026,
    monthIndex: 7,
    day: 11,
    hour: 18,
    minute: 0,
    timeZone: TZ,
    title: "The Dial @ City Lights — Mara Wilson with Saumya Roy",
    tagline: "City Lights · North Beach · Free",
    description: "Mara Wilson discusses How We See It: The World Looks at America in the Age of Trump.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-cole-nicole-lefavour-in-the-arms-of-moun-20260818",
    year: 2026,
    monthIndex: 7,
    day: 18,
    hour: 18,
    minute: 0,
    timeZone: TZ,
    title: "Cole Nicole LeFavour — In the Arms of Mountains",
    tagline: "City Lights · North Beach · Free",
    description: "Cole Nicole LeFavour discusses In the Arms of Mountains (Beacon Press).",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-a-igoni-barrett-whyteface-20260820",
    year: 2026,
    monthIndex: 7,
    day: 20,
    hour: 18,
    minute: 0,
    timeZone: TZ,
    title: "A. Igoni Barrett — Whyteface",
    tagline: "City Lights · North Beach · Free",
    description: "City Lights and Graywolf Press celebrate Whyteface by A. Igoni Barrett.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-haiku-in-the-alley-20260822",
    year: 2026,
    monthIndex: 7,
    day: 22,
    hour: 13,
    minute: 0,
    timeZone: TZ,
    title: "Haiku In The Alley",
    tagline: "City Lights · North Beach · Free",
    description: "Editors Susan Antolin, Garry Gay, and Carolyn Hall celebrate Bay Area haiku with local poets in Kerouac Alley.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-beyond-baroque-city-lights-20260823",
    year: 2026,
    monthIndex: 7,
    day: 23,
    hour: 12,
    minute: 0,
    timeZone: TZ,
    title: "Beyond Baroque @ City Lights",
    tagline: "City Lights · North Beach · Free",
    description: "Poetry in Kerouac Alley featuring Rhiannon Cielos Chavez, Genesis Perez, Iván Salinas, and jimmy vega.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-citylights-adrian-daub-what-tech-calls-governing-20260826",
    year: 2026,
    monthIndex: 7,
    day: 26,
    hour: 18,
    minute: 0,
    timeZone: TZ,
    title: "Adrian Daub — What Tech Calls Governing",
    tagline: "City Lights · North Beach · Free",
    description: "City Lights and Stanford University Press celebrate What Tech Calls Governing by Adrian Daub.",
    category: "reading",
    organizer: "City Lights Bookstore",
    venue: "City Lights Bookstore",
    address: "261 Columbus Ave, San Francisco, CA 94133",
    neighborhood: "North Beach",
    rsvpUrl: "https://citylights.com/events/",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-booksmith-read-my-lips-a-book-slut-drag-show-natur-20260723",
    year: 2026,
    monthIndex: 6,
    day: 23,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Read My Lips: A Book Slut Drag Show (Natural Beauty)",
    tagline: "The Booksmith · Haight · Ticketed",
    description: "Irreverent literary drag celebration at The Booksmith — one-year anniversary, Natural Beauty theme.",
    category: "other",
    organizer: "The Booksmith",
    venue: "The Booksmith",
    address: "1727 Haight St, San Francisco, CA 94117",
    neighborhood: "Haight",
    rsvpUrl: "https://booksmith.com/event/RML726",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "sf-booksmith-catherine-cho-with-sophie-wan-the-devote-20260728",
    year: 2026,
    monthIndex: 6,
    day: 28,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Catherine Cho with Sophie Wan — The Devoted",
    tagline: "The Booksmith · Haight · Free · RSVP",
    description: "Catherine Cho and Sophie Wan for the release of The Devoted. RSVP appreciated.",
    category: "reading",
    organizer: "The Booksmith",
    venue: "The Booksmith",
    address: "1727 Haight St, San Francisco, CA 94117",
    neighborhood: "Haight",
    rsvpUrl: "https://booksmith.com/event/2026-07-28/booksmith-presents-catherine-cho-sophie-wan-devoted",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-booksmith-william-archila-friends-can-cula-dog-day-20260729",
    year: 2026,
    monthIndex: 6,
    day: 29,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "William Archila & friends — Canícula / Dog Days",
    tagline: "The Booksmith · Haight · Free · RSVP",
    description: "William Archila celebrates Canícula / Dog Days with fellow writers.",
    category: "reading",
    organizer: "The Booksmith",
    venue: "The Booksmith",
    address: "1727 Haight St, San Francisco, CA 94117",
    neighborhood: "Haight",
    rsvpUrl: "https://booksmith.com/event/archila26",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-booksmith-danny-ramadan-with-zeina-hashem-beck-cro-20260820",
    year: 2026,
    monthIndex: 7,
    day: 20,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Danny Ramadan with Zeina Hashem Beck — Crooked Teeth",
    tagline: "The Booksmith · Haight · Free · RSVP",
    description: "Launch of Crooked Teeth with Zeina Hashem Beck.",
    category: "reading",
    organizer: "The Booksmith",
    venue: "The Booksmith",
    address: "1727 Haight St, San Francisco, CA 94117",
    neighborhood: "Haight",
    rsvpUrl: "https://booksmith.com/event/2026-08-20/booksmith-presents-danny-ramadan-zeina-hashem-beck-crooked-teeth",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-booksmith-laleh-khadivi-with-oscar-villalon-female-20260922",
    year: 2026,
    monthIndex: 8,
    day: 22,
    hour: 19,
    minute: 0,
    timeZone: TZ,
    title: "Laleh Khadivi with Oscar Villalon — Female Life on Planet Earth",
    tagline: "The Booksmith · Haight · Free · RSVP",
    description: "Launch of Female Life on Planet Earth with Oscar Villalon.",
    category: "reading",
    organizer: "The Booksmith",
    venue: "The Booksmith",
    address: "1727 Haight St, San Francisco, CA 94117",
    neighborhood: "Haight",
    rsvpUrl: "https://booksmith.com/event/khadivi26",
    sourceChannel: "bookstore",
    price: "free",
  },
  {
    id: "sf-booksmith-neal-stephenson-d-heavy-water-20261015",
    year: 2026,
    monthIndex: 9,
    day: 15,
    hour: 19,
    minute: 0,
    endHour: 21,
    endMinute: 0,
    timeZone: TZ,
    title: "Neal Stephenson — D: Heavy Water",
    tagline: "The Booksmith · Richmond · Ticketed",
    description: "Neal Stephenson for D: Heavy Water at The Internet Archive. Tickets required.",
    category: "reading",
    organizer: "The Booksmith",
    venue: "Internet Archive",
    address: "300 Funston Ave, San Francisco, CA 94118",
    neighborhood: "Richmond",
    rsvpUrl: "https://booksmith.com/event/stephenson26",
    sourceChannel: "bookstore",
    price: "paid",
  },
  {
    id: "sf-eb-city-slam-20260726",
    year: 2026,
    monthIndex: 6,
    day: 26,
    hour: 18,
    minute: 0,
    endHour: 21,
    endMinute: 30,
    timeZone: TZ,
    title: "The City Slam Poetry Slam and Experimental Open Mic",
    tagline: "Muddy Waters · Mission · Poetry slam · Eventbrite",
    description:
      "Poetry slam and experimental open mic at Muddy Waters Coffee & Lounge. " +
      "Slam sign-ups at 6pm; competition at 7pm. Competitors get free entry; cash prizes for winner and runner-up. " +
      "Open mic sign-up at the door.",
    category: "reading",
    organizer: "DC NOTE",
    venue: "Muddy Waters Coffee & Lounge",
    address: "521 Valencia St, San Francisco, CA 94110",
    neighborhood: "Mission",
    rsvpUrl:
      "https://www.eventbrite.com/e/the-city-slam-poetry-slam-and-experimental-open-mic-tickets-1993571464917",
    sourceChannel: "eventbrite",
  },
];

function mapSpec(spec: CuratedSpec): WorkshopEvent {
  const start = DateTime.fromObject(
    {
      year: spec.year,
      month: spec.monthIndex + 1,
      day: spec.day,
      hour: spec.hour,
      minute: spec.minute,
      second: 0,
      millisecond: 0,
    },
    { zone: spec.timeZone },
  );
  const end =
    spec.endHour != null
      ? DateTime.fromObject(
          {
            year: spec.year,
            month: spec.monthIndex + 1,
            day: spec.day,
            hour: spec.endHour,
            minute: spec.endMinute ?? 0,
            second: 0,
            millisecond: 0,
          },
          { zone: spec.timeZone },
        )
      : start.plus({ hours: 1 });

  const isGreenApple = /green apple/i.test(spec.organizer);
  const price = spec.price ?? (isGreenApple ? "free" : "unknown");
  let description = spec.description;
  if (/see listing for details\.?$/i.test(description.trim())) {
    description = isGreenApple
      ? description.replace(
          /\s*See listing for details\.?$/i,
          price === "free"
            ? " Free author event; please RSVP."
            : " See the Green Apple Books listing for details and RSVP.",
        )
      : description;
  }
  const tagline =
    price === "free" && isGreenApple && !/\bfree\b/i.test(spec.tagline)
      ? spec.tagline.replace(/ · RSVP$/i, " · Free · RSVP")
      : spec.tagline;

  return {
    id: spec.id,
    cityId: "sf",
    title: spec.title,
    tagline,
    description,
    start: start.toISO()!,
    end: end.toISO()!,
    timeZone: spec.timeZone,
    format: "in-person",
    price,
    category: spec.category,
    organizer: spec.organizer,
    venue: spec.venue,
    address: spec.address,
    neighborhood: spec.neighborhood,
    rsvpUrl: spec.rsvpUrl,
    source: "SF curated (Green Apple, Litquake, City Lights, Booksmith)",
    sourceChannel: spec.sourceChannel,
    listingProvenance: "live",
  };
}

export type CuratedMeta = {
  curatedTotal: number;
  rowsInMonth: number;
};

export function fetchSfCuratedEventsForMonth(
  year: number,
  monthIndex: number,
): { events: WorkshopEvent[]; meta: CuratedMeta } {
  const rows = CURATED.filter(
    (s) => s.year === year && s.monthIndex === monthIndex,
  );
  return {
    events: rows.map(mapSpec),
    meta: { curatedTotal: CURATED.length, rowsInMonth: rows.length },
  };
}
